### ISSUE TITLE
REST API for Guest+Host Responses

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#130]
### Overview
Create an implementation of the REST API for Guests' responses and the underlying Repository class for properly inserting, updating and reading data  to and from the 'guestResponses' collection in MongoDB

### Action Items
Create/update the following HTTP routes:
- [x] **GET /api/guests/<guest_id>/responses**
Return all responses for guest with ID of 'guest_id'

- [x] **GET /api/guests/<guest_id>/responses/<question_id>**
Return the indicated guest's response value to question with ID of 'question_id'

- [x] **POST /api/guests/<guest_id>/responses**
Add a response for the indicated guest

- [x] **PUT /api/guests/<guest_id>/responses/<question_id>**
Update a guest's response to question with ID of 'question_id'

- [x] **DELETE /api/guests/<guest_id>/responses/<question_id>**
Delete a guest response by question ID

- [x] **GET /api/hosts/<host_id>/responses**
Return all responses for host with ID of 'host_id'

- [x] **GET /api/hosts/<host_id>/responses/<question_id>**
Return the indicated host's response value to question with ID of 'question_id'

- [x] **POST /api/hosts/<host_id>/responses**
Add a response for the indicated host

- [x] **PUT /api/hosts/<guest_id>/responses/<question_id>**
Update a host's response to question with ID of 'question_id'

- [x] **DELETE /api/hosts/<host_id>/responses/<question_id>**
Delete a host response by question ID

**Comment by KarlenS** [comment]
expanded scope to include mirror response routes for hosts
