### ISSUE TITLE
Complete REST API implementation for Hosts and Host Questions

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#132]
### Overview
Implement support for I/O on hosts and host questions using MongoDB, abstracted using Repository interface

### Action Items
- [x] **GET /api/hosts**
Get all hosts

- [x] **GET /api/hosts/<host_id>**
Get a single host by ID

- [x] **POST /api/hosts/**
Add a host

- [x] **PUT /api/hosts/<host_id>**
Update a Host by ID

- [x] **DELETE /api/hosts/<host_id>**
Delete a Host by ID

- [x] **GET /api/hostQuestions**
Get all HostQuestions

- [x] **GET /api/hostQuestions/<id>**
Return host question by ID

- [ ] *GET /api/<org_id>/hostQuestions*
Get all HostQuestions for the indicated organization

**Comment by tylerthome** [comment]
As of the recent changes submitted by @KarlenS in PR #161 this issue is resolved, noting that support for associating these resources to an Organization is being deferred for the time being.

**Comment by lola3736** [comment]
@tylerthome please review complexity and points label for accruacy.
