### ISSUE TITLE
Define user correspondence mechanism(s) including email, social and SMS

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#135]
### Overview
The HomeUnite.Us system requires a protocol for automated correspondence with users, including registration links and notifications/alerts. Define the use cases for directly messaging users, and the platforms (e.g. social media, email) most suitable for each.

**Comment by c-fuchs** [comment]
Per team call on 5/12, Auth0 will handle automated emails for login creation, lost password, etc.

Other automated emails to be generated:
1) when the profile is complete and submitted to SPY for review
2a) when the profile has been reviewed by SPY and is kicked back to the user for an update (provide a reason for being kicked back)
2b) as a host, when the host profile has been approved by SPY and each next step (background check, interview, home visit) needs to be completed
2c) as a guest, when the guest profile has been approved by SPY and the guest is able to view and match with hosts
3) as a host, when the host has been selected by a guest, the host should be prompted to view the guest profile
4) for both guests and hosts, when mutual interest is indicated both users should receive an email to set up a meeting with the case worker present

**Comment by ExperimentsInHonesty** [comment]
We are deferring any social media integration until after MVP.  However, guest and hosts should be able to receive sms messages through the system emailing their phone@providerurl and that will send them a sms message to login to the app
https://20somethingfinance.com/how-to-send-text-messages-sms-via-email-for-free/

**Comment by lola3736** [comment]
@tylerthome please review the complexity, feature and point label for accuracy.
