### ISSUE TITLE
Prototype initial testing infrastructure for front end

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#136]
### Overview
Design and document an overall approach for automated testing for the front end application. Develop an example unit test suite on a React component of your choosing (or create an example component to test)

### Action Items
- [x] Create/update the CONTRIBUTING.md file to include a section on Unit Testing, which should explain what unit tests developers are responsible for submitting for a feature specification
- [ ] Update the README.md to describe the overall approach to testing (e.g. integration testing and CI/CD), and how to run the test suite(s) during development
- [x] Write a test suite which exemplifies the preferred conventions for a simple React component

**Comment by tylerthome** [comment]
@arshiamasih @ExperimentsInHonesty pending discussion on the importance of this for MVP phase for prioritization

**Comment by ExperimentsInHonesty** [comment]
As soon as we have a developer who wants to take implementing testing on, lets connect them with Rich Crook who setup 311's  testing suite.  This is his expertise.

**Comment by erikguntner** [comment]
I setup Jest, React Testing Library and Cypress with simple example tests. The Read me still needs to be updated with commands and information around testing.

**Comment by lola3736** [comment]
@tylerthome please review complexity label for accuracy.
