### ISSUE TITLE
Create userflow of Guest sign up wizard

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#139]
### Overview
Create a userflow for the sign up wizard Guests will use when they log in to the app the first time, with questions. 

### Action Items

- [x] Create wireframes for sign up wizard
1) Navigation with notes like "Page 5 of 7"
2) Image upload
3) See Food Oasis for sign up flow
4) Back, Skip, Save & Continue
5) If user leaves the wizard, what sort of message/warning will they get 

- [x] Create list of which questions guests will be asked on each page

- [ ] Define what users will see when they exit the wizard:
1) After all questions completed: review profile and "publish" or "confirm" option
2) With all filtering questions complete, but some non-filtering questions missing information: review profile with missing fields highlighted, and confirm/publish option active
3) With some filtering questions missing information: send user back to appropriate step in the wizard, review profile confirm/publish option inactive

### Resources/Instructions
[SPY Style Guide](https://www.figma.com/file/c9NcMJwWjbFFqB4PWcKqFf/Site-Pages--Working-Version?node-id=0%3A1)
[Old SMILE app wireframes](https://www.figma.com/file/SUrFxtWMxNz57mZlGeTiAD/SMILE-Demo?node-id=26%3A3610)
[Guest questions spreadsheet](https://docs.google.com/spreadsheets/d/19jHgjezTa3uI91Tj2sHFcYVu65QpdfHBOrOhDB5iUIo/edit#gid=0)
[SPY guest application](https://drive.google.com/drive/u/0/folders/1PZzzGa8yEPn-wNEibCSDQkP3KikMs73e)
[Point Source Youth guide for Host Home projects, page 107](https://drive.google.com/drive/u/0/folders/1ahxiD9rIsBtx0yAPlPcPaGw8zGrfHHm9)
List of filtering questions from backend

**Comment by abbyhipp** [comment]
Will be replaced with a new issue that is more clear
