### ISSUE TITLE
Create wireframes for Host sign up wizard

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#140]
### Overview
Create wireframes for each step of the Host sign up wizard, with relevant questions. 

### Action Items

- [x] Create wireframes for Host sign up wizard
1) Image upload
2) Navigation with "Page 5 out of 7" or similar
3) Options for Back, Skip, and Save & Continue
4) See Food Oasis for other sign up steps

- [x] Create list of questions Hosts will be asked upon sign up
    Break out filtering questions vs non-filtering questions
    Demonstrate what questions will be on each page of the sign up wizard

- [ ] Define what users will see when they exit the wizard:
1) With all questions completed: Review profile and obvious CTA to submit application
2) With filtering questions completed but some non-filtering questions missing: Review profile with clear markers for missing information, "submit application" available
3) With some filtering questions missing: Return user to relevant question in the wizard, profile's "submit application" stays inactive 

### Resources/Instructions
[Style Guide](https://www.figma.com/file/c9NcMJwWjbFFqB4PWcKqFf/Site-Pages--Working-Version?node-id=0%3A1)
[Old SMILE app wireframes](https://www.figma.com/file/SUrFxtWMxNz57mZlGeTiAD/SMILE-Demo?node-id=26%3A3610)
[Host questions spreadsheet](https://docs.google.com/spreadsheets/d/1pNWAsPqTCTk2QBGTx5TPTte8qiMI1pCYOp_CoA2Z6jw/edit#gid=0)
[SPY Host application, pages 6-11](https://drive.google.com/file/d/0B3o4rAE_DB1IeTFGX3J3ZjNPblo3OE13a0xrX28xVW5hOHRv/view)
List from backend for filtering vs non-filtering questions 
[Point Source Youth Host application, page 25](https://drive.google.com/drive/u/0/folders/1ahxiD9rIsBtx0yAPlPcPaGw8zGrfHHm9)

**Comment by abbyhipp** [comment]
This has been completed
