### ISSUE TITLE
Create ERD or data map

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#147]
### Overview
Create a process flow diagram to describe what places different types of data come from and how they interact. 

### Action Items
REPLACE THIS TEXT -If this is the beginning of the task this is most likely something to be researched and documented.

REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by KarlenS** [comment]
![HomeUniteUsProcessFlow](https://user-images.githubusercontent.com/7812196/82400950-83451980-9a26-11ea-823e-34d9a91b9be9.png)

Also included the diagram in the drive:
https://drive.google.com/file/d/1E8fuklHnxX5HXCafM04nusj3UHqyRUm7/view?usp=sharing
