### ISSUE TITLE
Auth: verify and redirect user

### ISSUE THREAD

**Issue by arshiamasih** [hackforla/HomeUniteUs#152]
upon login, authentication should verify whether 1. the user has an existing account and 2. if the user's profile has been completed (no skips/pending questions open).

if verified as an existing user with a completed profile, user should be kicked straight to their profile. otherwise, user should 

if no account/user:
go to the profile selection to register

if an account but incomplete registration:
somewhere in the registration flow, possibly the final profile submit page which would highlight all missing items. for now we can dummy as an empty component. 

**frontend:** @HassenH1 
(upon login) create the calls to verify user and logic to send client to respective pages based on above 

**backend:** @KarlenS @tylerthome 
set up routes, and any necessary persistent data points in the model/db

this is a full stack issue and should function front to back/ back to front successfully

**Comment by tylerthome** [comment]
As of PR #175 by @HassenH1 this issue is nominally resolved, noting that a future iteration will integrate authorization features of Auth0 via scopes and roles.

**Comment by lola3736** [comment]
@tylerthome please review points and complexity label for accuracy.
