### ISSUE TITLE
Registration flow - Client side validation

### ISSUE THREAD

**Issue by arshiamasih** [hackforla/HomeUniteUs#154]
### Overview 

Apply client-side validation to forms for responsive user experience when data would not be accepted by the webservice

### Actions
Using the existing component library, create the Form components for Host Details including the following input fields with appropriate validation

Refer to the Hi Fi Prototype diagram on the following Figma board: https://www.figma.com/file/5uXe3GeE99l16uBf5hucWb/Home-Unite-Us?node-id=542%3A180

- [x] Host Bio/Information
  - [x] Formik Validation: First Name, Last Name not blank
  - [x] Formik Validation: Birth date is valid (i.e. date less than current date)
- [x] Host Bio/Address
  - [x] Formik Validation: Street Address 1 not blank
  - [x]  Formik Validation: City, State and Zip not blank 
- [x] Contact/Information
  - [x] Formik Validation: Email is valid
  - [x] Custom Validation: At least one Phone Number is provided
  - [x] Formik Validation: Phone number is valid, if provided

**Comment by tylerthome** [comment]
@HassenH1  Update for iteration #2 of registration user flow:

Using the existing component library, create the Form components for Host Details including the following input fields with appropriate validation

Refer to the Hi Fi Prototype diagram on the following Figma board: https://www.figma.com/file/5uXe3GeE99l16uBf5hucWb/Home-Unite-Us?node-id=542%3A180

- [ ] Host Bio/Information
  - [ ] Formik Validation: First Name, Last Name not blank
  - [ ] Formik Validation: Birth date is valid (i.e. date less than current date)
- [ ] Host Bio/Address
  - [ ] Formik Validation: Street Address 1 not blank
  - [ ]  Formik Validation: City, State and Zip not blank 
- [ ] Contact/Information
  - [ ] Formik Validation: Email is valid
  - [ ] Custom Validation: At least one Phone Number is provided
  - [ ] Formik Validation: Phone number is valid, if provided

**Comment by HassenH1** [comment]
I will be push a PR soon
I just have to complete Draggable component for the ordering the best contact information section

**Comment by quyenvhle** [comment]
@tylerthome could you check to see if we can close this issue?
