### ISSUE TITLE
registration questions in database

### ISSUE THREAD

**Issue by arshiamasih** [hackforla/HomeUniteUs#156]
### Overview

We want to create registration questions in the database that follow this model as defined by frontend wireframes.

### Actions

- [x] Create a JSON representation of the question data
- [x] Update the seed script to enter the questions into the MongoDB 
- [x] Release dependency on #173 for this issue (mark it in top section under actions.  If both are released, move that issue to prioritized backlog.

### Resources
Model as defined by frontend:

'answer' defaults to null. for now we are going with each 'next' will submit and send the answer back to the server. 

'type': ['radio', 'dropdown', 'text', 'checkbox', 'form']

questions and 'options' (answer options for dropdown/radio/checkbox) have been provided by @c-fuchs 

export interface Question {
    id: string,
    question: string,
    type: string,
    options?: Array<any>,
    answer?: any
}

[Profile Questions](https://docs.google.com/spreadsheets/d/1GNrVweD7aRmSEAnA39Z59p3zwopLi87VVrahqlgI5G8/edit#gid=0)

**Comment by arshiamasih** [comment]
keep in mind we might need a category for question groupings. subcategories for where in the flow, and categories of questions that might get grouped together, per the current design layout.

**Comment by c-fuchs** [comment]
Registration questions here:
https://docs.google.com/spreadsheets/d/1GNrVweD7aRmSEAnA39Z59p3zwopLi87VVrahqlgI5G8/edit#gid=1757343176

**Comment by KarlenS** [comment]
I added two additional sheets (one for host and one for guest) in the document to try to capture all of the data necessary for the frontend that will be captured in the database and fed through the API. I'll need input from frontend and UX on some of the fields - will discuss during the meetings.

**Comment by ExperimentsInHonesty** [comment]
@KarlenS please update
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by abbyhipp** [comment]
Seed scripts have been updated and questions in the database
