### ISSUE TITLE
Refactor back-end directory structure via logically separated Python modules 

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#168]
### Overview
Create a logical separation of the components currently in the all-encompassing hosthome.py file, move those into dedicated Python modules in a tree of subdirectories, and add the necessary import statements.

### Action Items
* Separate MongoDB utilities
* Separate data access interface(s) , import mongo
* Trim hosthome.py to purely concern itself with route management and initialization logic, importing necessary utilities from subpackages

**Comment by tylerthome** [comment]
Recommend deferring this ticket to post MVP (or at least after Host Registration milestone), currently almost all server-side code is in one Python file and this restructuring should be assigned high importance and urgency once current milestone is reached.

**Comment by ExperimentsInHonesty** [comment]
@tylerthome @abbyhipp lets talk about prioritization of this on Saturday

**Comment by abbyhipp** [comment]
Refactored backend structure and it has been committed

**Comment by lola3736** [comment]
@tylerthome please review complexity and points label for accuracy
