### ISSUE TITLE
Create a logo for HomeUnite.Us

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#171]
### Overview
Create a logo for the HomeUnite.Us team, to replace our current placeholder image and connect better with the project themes and Hack for LA design feel. 

### Action Items
Create a logo for the HomeUnite.Us project
The logo: 
1. Should feature imagery of housing, community, housing access, and/or positive change
2. Should communicate feelings of progress, empowerment, community connections, and/or safety
3. Should _not_ look like the SPY logo, in color or other design elements
4. _Should_ incorporate some elements (colors, shapes, font, layout) of the Hack for LA logo

### Resources/Instructions
Hack for LA logo- incorporate some of these elements
![image](https://user-images.githubusercontent.com/24849648/83318748-72e22b00-a1ec-11ea-8878-10e1de70da08.png)

SPY logo- make sure it doesn't look too much like this
![image](https://user-images.githubusercontent.com/24849648/83318759-a0c76f80-a1ec-11ea-8a25-aecf75dce866.png)

**Comment by abbyhipp** [comment]
The Logo has been created 
![HUU-Logo V1 (1) (1)](https://user-images.githubusercontent.com/69595646/103464564-8eb13080-4ce9-11eb-8d11-2188e1c8b8b5.png)
