### ISSUE TITLE
Optimize SQL queries

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#173]
### Dependency
pending resolution of issues
#156  - Completed
#194 - Completed

### Overview
Improve the data access layer implementation by leveraging mongo's collection query API more effectively

### Action Items
- [ ] Confirm #156  is released 
- [ ] Confirm #194 is released
- [ ] Identify cases where data-access module(s) are using naive `find({})` queries, and their callers which do not actually want all fields of all records in collection
- [ ] Extend module to more explicitly support these use cases

### Resources/Instructions
https://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection

**Comment by tylerthome** [comment]
@KarlenS  pending resolution of issue #156  and #194 so that we understand what use cases to support

**Comment by ExperimentsInHonesty** [comment]
@tylerthome does this issue need other labels?  

The other tickets have the following labels:
**#156**

- Feature: Guest Registration
- Feature: Host Registration
- Back End

**#194**

- Feature: Architecture
- Front End

**Comment by kpoints** [comment]
Obsolete as we're moving away from MongoDB.
