### ISSUE TITLE
Design a user interface for making 2-party appointments

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#184]
### Overview
Our app will have several types of appointments scheduled with the case worker and EITHER the Host or Guest. Design a user interface for the Host/Guest to schedule these. 

### Action Items
Design a UI so that a user can: 
1) View a calendar of the case worker's availability for that type of appointment
2) Select a time slot for their appointment. The duration of the appointment will be predetermined.
3) Schedule the appointment time
4) Receive a confirmation with a calendar event they can add to their personal google/outlook/apple calendar

### Resources/Instructions
[Tracy's product spec for Nylas](https://docs.google.com/document/d/1tSwq2xJ9gkjxXfvtzHLR4jXZtEduuyNUYAJ0S4omTi4/edit)

**Comment by ExperimentsInHonesty** [comment]
Has been replaced by calendaring
