### ISSUE TITLE
Design a user interface for scheduling 3-party appointments

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#185]
### Overview
Our app will have at least one type of appointment scheduled with the case worker and BOTH the Host AND Guest. Design a user interface for the Host and Guest to schedule these. 

### Action Items
Design a UI so that a user can: 
1) View a calendar of the availability for that type of appointment. There should be a notification that the page will time out after 30 minutes of inactivity.
2a) (First to view calendar) Select 3-5 time slots for the appointment. The duration of the appointment will be predetermined. Confirmation message that the times are saved.
2b) (Next to view calendar after 2a is done by the other user) Select 1 time slot from the 3-5 slots previously selected by the other user. 
3) Schedule the appointment time selected in 2b
4) Both users receive a confirmation with a calendar event they can add to their personal google/outlook/apple calendar

### Resources/Instructions
Dependent upon team deciding how to handle order of 3-party appointment scheduling

[Tracy's product spec for Nylas](https://docs.google.com/document/d/1tSwq2xJ9gkjxXfvtzHLR4jXZtEduuyNUYAJ0S4omTi4/edit)

**Comment by ExperimentsInHonesty** [comment]
Has been replaced by calendaring
