### ISSUE TITLE
Update progress bar with milestones/steps in wireframes

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#187]
### Overview
Add steps into the progress bar to show sign up flow stages.

### Action Items
Add steps to progress bar to mark progress through the sign up stages

### Resources/Instructions
![image](https://user-images.githubusercontent.com/24849648/83960813-eebe2200-a841-11ea-894c-1cc55bdfad82.png)

**Comment by quyenvhle** [comment]
Close. We don't use this anymore.
