### ISSUE TITLE
Design a home page for Guests

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#189]
### Overview
Design a homepage for Guests to see after they've completed the sign in wizard, to track their progress through the matching process. 

### Action Items
Study the Guest application process 
Design a home page for Guests to see their current status, completed steps, next steps, and links to any outside resources needed to complete steps

### Resources/Instructions
[Initial wireframe of Guest homepage](https://www.figma.com/file/xIMx6SFw9AFQoZoHpzdcpi/Login-userflows?node-id=135%3A0)

**Comment by abbyhipp** [comment]
Guest Dashboard has been made in Figma

**Comment by lola3736** [comment]
This issue has been replaced with [#533 Section 2 Guest Intake Profile (fka Application Form)](#533).
