### ISSUE TITLE
Create React Context for Guest Dashboard Module

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#193]
### Overview
Create a custom hook for the Guest Dashboard, wrapping a context provider with internal state management and API integration

### Dependency
pending resolution of issue #194

### Action Items
- [ ] Confirm #194 is released
- [ ] Scaffold context provider with internal state
- [ ] Add custom hook to expose context with semantics relevant to business information 
- [ ]  Ensure hook and context are sufficiently flexible for future requirements changes

**Comment by tylerthome** [comment]
pending resolution to #194 and will closely follow implementation of Host Dashboard context being developed by @arshiamasih

**Comment by abbyhipp** [comment]
@tylerthome What feature label should this get?

**Comment by lola3736** [comment]
@tylerthome @lasryariel @lola3736 
Need to confirm points and complexity.
