### ISSUE TITLE
Create image uploader component for user profile picture

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#205]
### Overview
Create a React component with a file input element, capturing the `File` object in component state.

### Resources/Instructions
* Docs:
  * Input: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
  * File API: https://developer.mozilla.org/en-US/docs/Web/API/File
* JavaScript React Example: https://medium.com/trabe/controlled-file-input-components-in-react-3f0d42f901b8

**Comment by HassenH1** [comment]
This issue is done
