### ISSUE TITLE
Prepare EC2 instance for application deployment

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#206]
### Overview
We need to host HomeUniteUs on AWS so the project complies with HackForLA Standards and benefits from centralized management.

### Action Items
Perform all installations, configurations and an initial deployment of Home Unite Us within the EC2 instance on AWS

* Install and configure nginx
* Install Python 3 and system dependencies
* Create and install application dependencies in virtual environment

### Resources/Instructions
* Python/Flask on Ubuntu: https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04
* Nginx with server blocks: https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-18-04#step-5-setting-up-server-blocks-(recommended)
* SSL for HTTPS traffic: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04

**Comment by abbyhipp** [comment]
As per Tyler this is complete.

**Comment by lola3736** [comment]
@tylerthome please review complexity and points label for accuracy.
