### ISSUE TITLE
Reconcile issues not showing up on any project board

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/HomeUniteUs#210]
### Overview
There are open issues that are not on the project boards.

### Action Items
- [x] review the missing issues
- [x] assign them to the appropriate boards, or close them.

### Resources/Instructions
https://github.com/hackforla/HomeUniteUs/issues?q=no%3Aproject+type%3Aissue+is%3Aopen+

**Comment by abbyhipp** [comment]
All the issues that were not assigned to any board have been assigned to a board or closed
