### ISSUE TITLE
Calendar - Wireframes

### ISSUE THREAD

**Issue by kiyanac** [hackforla/HomeUniteUs#213]
Create wireframe flows for: 

- [x] Home Owner
- [x] Guest 
- [x] Case Worker

[See FIGMA file here for reference.](https://www.figma.com/file/FrIY32ZqKGJxl3VQNoGgPg/Calendaring-Home-Unite-Us?node-id=140%3A410)

**Comment by ariamacabre** [comment]
Link to Figma - Case Worker still in progress: https://www.figma.com/file/FrIY32ZqKGJxl3VQNoGgPg/HomeOwner-Guest-Scheduling-Appointment-Type-Screen-Copy?node-id=22%3A2

**Comment by ExperimentsInHonesty** [comment]
Looks fantastic!  Great work!!!!
