### ISSUE TITLE
Extend ApiWrapper to support fetching MatchingQuestion, QualifyingQuestion

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#216]
### Overview
Add ApiWrapper logic to HTTP fetch, JSON parse and return TS objects for the newly-created MatchingQuestion and ShowstopperQuestion interfaces

### Action Items
- [ ] Add `getShowstopperQuestions` to return `Array<ShowstopperQuestion>`
- [ ] Add `getMatchingQuestions` to return `Array<MatchingQuestion >`

### Resources
* Study the corresponding Flask API endpoint to appropriately call and handle the logic at the HTTP layer

**Comment by ExperimentsInHonesty** [comment]
@tylerthome does this need to be in the UAT column?
