### ISSUE TITLE
Update hifi prototype with gender neutral images

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/HomeUniteUs#220]
### Overview
Create new imagery with gender neutral people to resonate with all communities.

### Action Items

- [ ] Add copies of screens with new images above existing screens.
   - [ ]  remove gender
   - [ ] family size is more likely to be two adults

### Resources/Instructions
https://www.figma.com/file/5uXe3GeE99l16uBf5hucWb/Home-Unite-Us?node-id=542%3A180

**Comment by amimorga** [comment]
Decided to move forward with a house icon or gender-neutral icon. Waiting for feedback from the group but have some options.

**Comment by ExperimentsInHonesty** [comment]
@amimorga Please link to where your drafts are

**Comment by ExperimentsInHonesty** [comment]
![Screen Shot 2020-08-18 at 5 07 35 PM](https://user-images.githubusercontent.com/37763229/90577290-54e5f000-e175-11ea-8d3a-de9db61cbadd.png)
![Screen Shot 2020-08-18 at 5 08 09 PM](https://user-images.githubusercontent.com/37763229/90577317-6a5b1a00-e175-11ea-8e96-86d4d6c0ee18.png)
![Screen Shot 2020-08-18 at 5 08 39 PM](https://user-images.githubusercontent.com/37763229/90577347-7c3cbd00-e175-11ea-8567-a3ff683a4f9c.png)
![Screen Shot 2020-08-18 at 5 09 10 PM](https://user-images.githubusercontent.com/37763229/90577369-8d85c980-e175-11ea-8ab0-b4149a9dd3de.png)
![Screen Shot 2020-08-18 at 5 09 31 PM](https://user-images.githubusercontent.com/37763229/90577386-99718b80-e175-11ea-80f1-edcce5a214b1.png)
![Screen Shot 2020-08-18 at 5 09 55 PM](https://user-images.githubusercontent.com/37763229/90577403-a7bfa780-e175-11ea-9e45-f522e3177652.png)
![Screen Shot 2020-08-18 at 5 10 14 PM](https://user-images.githubusercontent.com/37763229/90577416-b4dc9680-e175-11ea-8244-99c320f3f0f6.png)
![Screen Shot 2020-08-18 at 5 10 38 PM](https://user-images.githubusercontent.com/37763229/90577431-c1f98580-e175-11ea-99c9-180a4647a313.png)
![Screen Shot 2020-08-18 at 5 10 59 PM](https://user-images.githubusercontent.com/37763229/90577453-ce7dde00-e175-11ea-9a2d-85810a305c18.png)
![Screen Shot 2020-08-18 at 5 11 23 PM](https://user-images.githubusercontent.com/37763229/90577475-dccbfa00-e175-11ea-9523-fbbf0115693e.png)
![Screen Shot 2020-08-18 at 5 11 42 PM](https://user-images.githubusercontent.com/37763229/90577494-e8b7bc00-e175-11ea-96ce-2f5ae547b38a.png)
![Screen Shot 2020-08-18 at 5 12 03 PM](https://user-images.githubusercontent.com/37763229/90577509-f40ae780-e175-11ea-82df-c799627dd5af.png)
![Screen Shot 2020-08-18 at 5 12 26 PM](https://user-images.githubusercontent.com/37763229/90577530-01c06d00-e176-11ea-9499-be860727ee09.png)
![Screen Shot 2020-08-18 at 5 14 11 PM](https://user-images.githubusercontent.com/37763229/90577604-45b37200-e176-11ea-9c9a-bfcb6f527520.png)
![Screen Shot 2020-08-18 at 5 14 44 PM](https://user-images.githubusercontent.com/37763229/90577846-b0fd4400-e176-11ea-9a4b-eff39921f4a1.png)
![Screen Shot 2020-08-18 at 5 18 36 PM](https://user-images.githubusercontent.com/37763229/90577923-e30ea600-e176-11ea-8274-2245db6c885c.png)
![Screen Shot 2020-08-18 at 5 19 08 PM](https://user-images.githubusercontent.com/37763229/90577947-f3268580-e176-11ea-99cd-f367440b5691.png)

**Comment by amimorga** [comment]
Here is what we decided to go with for the gender-neutral icons. I am ok with this for now but would like to circle back to it again. 
[https://www.figma.com/file/LkZFiVoZsLF3mEYbNJ7Qq2/Home-Unite-Us-Copy?node-id=542%3A180](https://www.figma.com/file/LkZFiVoZsLF3mEYbNJ7Qq2/Home-Unite-Us-Copy?node-id=542%3A180)
