### ISSUE TITLE
Home Picture Uploader

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#221]
### Overview
We need to have a method to upload photos to be displayed on the Host profile.

### Action Items
Integrate the file upload component into a view for for the Home Photos for the Host Registration flow
Make sure the new component is able to:

- [x] Upload and store multiple images in component state
- [x] Matches the wireframe diagram (linked below)
- [x] Has access to the API Wrapper module for uploading up confirmation by user

### Resources/Instructions

Create the view specified in [this wireframe diagram](https://www.figma.com/file/5uXe3GeE99l16uBf5hucWb/Home-Unite-Us?node-id=542%3A180), using the new file uploader component

![image](https://user-images.githubusercontent.com/9952154/89951840-feab0700-dbe0-11ea-8ad7-d0219798f234.png)

**Comment by abbyhipp** [comment]
Has been completed per #251
