### ISSUE TITLE
Create Host Registration components for types other than multiple choice

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#222]
### Overview
We need to create bespoke form components for questions allowing for custom validation.
### Action Items
Using the UI specification, modify the existing Host Bio input forms to complete the required presentation and functionality
- [x] HostBio/Information
- [x] HostBio/Address
- [x] HostBio/Language
- [x] HostBio/Gender

### Resources/Instructions
Following the wireframe diagrams [here](https://www.figma.com/file/5uXe3GeE99l16uBf5hucWb/Home-Unite-Us?node-id=542%3A180), create the components supporting the input for Host Bio

**Comment by HassenH1** [comment]
Can I close this one?
