### ISSUE TITLE
Point HomeUnite.us domain to EC2 instance

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#223]
### Overview
Configure the registrar to point to the nameserver for the EC2 instance for HomeUnite.us

### Action Items
- Add these nameservers in the registrar configuration for HomeUnite.us:
  - [x] ns-1163.awsdns-17.org
  - [x] ns-369.awsdns-46.com
  - [x] ns-1000.awsdns-61.net
  - [x] ns-1979.awsdns-55.co.uk

**Comment by ExperimentsInHonesty** [comment]
I have changed the name servers.  It will take up to 48 hours for it to resolve.

**Comment by abbyhipp** [comment]
It is resolving

**Comment by lola3736** [comment]
@tylerthome please review the complexity and points label for accuracy.
