### ISSUE TITLE
Update the wiki and hfla website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/HomeUniteUs#225]
### Overview
We need to be able to communicate project structure to onboard team members easily and keep the hack for la website up to date.

### Action Items

- [x] Define team members and get hfla website updated
- Tyler - Tech Lead
- Abby - Product Manager
- Tracy - Calendaring Team Lead
- [x] Define Stakeholders and add to WIKI
- Point Source Youth (National Stakeholder)
- Spy (local stakeholder)
- [x] Update wiki pages for each type of team member onboarding
- [x] Make resources section of Wiki
   - [x] Add link to Figma Basics
- [x] Add link to Figma Basics to the Joining the Team Lets Go section
- [x] Add link to the Wireframing in Figma to the Designer Wiki
- [x] Update what HH means in wiki

### Resources/Instructions
[Project Boards](https://github.com/hackforla/HomeUniteUs/projects/3)
[HomeUniteUs project page on hackforla.org](https://www.hackforla.org/projects/home-unite-us)
[HackforLA.org wiki](https://github.com/hackforla/website/wiki)
[Figma basics](https://www.figma.com/file/EjnrqEQ5wfNkdMQ7mVfgaL/Figma-Basics?node-id=0%3A286)

**Comment by abbyhipp** [comment]
This has been completed and has been updated with this ticket https://github.com/hackforla/website/issues/953#issuecomment-764840726
