### ISSUE TITLE
Migrate Auth0 register/login module to customized integration

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#227]
### Overview
Migrate the Auth0 login/register flow away from the default redirect-based module

### Resources/Instructions
Use [regular web app](https://auth0.com/docs/quickstart/webapp/python) integration or, if possible, roll a customized version of the PKCE code flow used underneath the default [redirect-based auth](https://auth0.com/docs/quickstart/spa/react)

**Comment by ExperimentsInHonesty** [comment]
@tylerthome why is this in the icebox? Is it a priority thing?

**Comment by tylerthome** [comment]
@ExperimentsInHonesty  I put this in the icebox because it is not an explicit requirement for the current milestone, Host Registration. That was the main criteria I was considering to distinguish between the icebox vs priority backlogs. 

It is absolutely a priority item, as you noted that attempting to register with an email that already has an account gives an unhelpful error message "Something went wrong. Try again." and we'd like more control over that experience

**Comment by tylerthome** [comment]
Moving this issue to MVP as it is a prerequisite for correct scopes and roles enforcement at the API layer. Also related to to issue #258

**Comment by ExperimentsInHonesty** [comment]
@tylerthome Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by lola3736** [comment]
@tylerthome please review the complexity label for accuracy.
