### ISSUE TITLE
Top-level Questions for Host Dashboard: Registration Module

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#229]
### Overview
Create a wireframe diagram for the top-level host registration questions, as distinguished by category

#### Category: Bio
  7: Full name
  16: Date of birth
  17: Gender
  18: Do you have another family member to add?
  19: Contact email
  20: Contact phone
  21: Preferred contact method
  22: Contact Address
  25: Is your contact address the same as your residential address?
  29: Housing Type
  32: Are you interested in being a temporary (1-10 days) or full time host (3-6 months)?
  33: Job

#### Category: Home
  35: Pet
  39: Guest Pet
  42: Smoking
  44: Drinking
  47: Substances
  50: How many youth are you able to host at one time?
  51: Are you willing to host a parenting youth?
  52: Are you willing to host youth who are in a relationship with one another?
  53: Please upload an image of yourself (feel free to include any other family members!)
  54: Please upload an image of your home
  55: Please upload any additional images you feel will give guests a better idea of you and your home

#### Category: Personal
  58: What are your passions, interests, and hobbies?
  59: What languages do you speak at home
  60: Describe any preferred or ideal characteristics you hope for in a guest
  61: Please share why you are interested in hosting a young person experiencing homelessness
  62: Please share any strengths, skills, or experience you have that you believe will make you a successful host
  63: Please describe any challenges you foresee in your role as host
  64: As a way of starting your host profile, please take a moment to write something to introduce yourself to potential guests. Feel free to talk about your passions and hobbies, your family, your home values, or anything else that feels important to you.

#### Category: Qualifying
  10: Do you have an extra bedroom or private space in your home?
  11: Are you able to provide Guest with access to a kitchen in which to prepare meals, store food and access to shared or private bathroom?
  12: Do you have homeowners/renters insurance?
  13: Do you live on the westside of Los Angeles or within reasonable distance to public transportation?
  14: Are you able and willing to pass a LiveScan background clearance check?
  15: Do you agree to complete this application, undergo and interview and a home inspection?
  1: Do you agree to attend a 3-hour SPY Volunteer Orientation and a 1-day Host Home Orientation Training?
  2: Do you commit to attending monthly meetings with SPY staff and other hosts?
  3: Do you commit to providing a welcoming, safe, non-judgmental environment and to supporting the self-determined goals of youth Guest?

**Comment by ExperimentsInHonesty** [comment]
@tylerthome why is this in the icebox? Is it a priority thing?

**Comment by tylerthome** [comment]
@ExperimentsInHonesty  This should be in the prioritized backlog, or possibly "in progress" as I believe that @amimorga is already working on this. Since it is not a development task I just marked assigned it to the project and likely defaulted to icebox

**Comment by amimorga** [comment]
Where can I see the sub-questions for some of these? @ExperimentsInHonesty you will also like these to be editable in the application tab of the dashboard?

**Comment by tylerthome** [comment]
@amimorga  As for the initial question lists (from which this list was generated), I can generate a version which also lists the subquestions for a general idea. These were written by one of our developers so the final version may be slightly different, but the categorical structure should hold.

**Comment by amimorga** [comment]
@tylerthome Thanks! Abby and I will be going through the questions this evening. The co-host questions were not accounted for in the flow and design.

**Comment by eq2thex** [comment]
@amimorga @tylerthome Please provide update 
1. Progress
2. Blocker
3. Availability
4. ETA
