### ISSUE TITLE
Initial Scaffolding for Host Dashboard view

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#236]
### Overview
Create a Host Dashboard page with sufficiently modular components to support ongoing design changes

### Action Items
Host Dashboard page should demonstrate the following capabilities:

- [ ] Display Host Questions with user responses in an abstracted list view, sample implementation should define props contract with top-level component 

- [ ] Clicking a Host Question + Response should route to corresponding location in Host Registration module

- [ ] Skipped/unanswered questions should be visibly distinguishable from questions with complete responses. A top-level question with unanswered conditional subquestions should be considered unanswered

### Resources/Instructions

As the initial UI specification is subject to change, abstract the presentation details into components relying solely on props. Sample subcomponent implementation may be implemented as `<table>` , `<ol>` , `<dl>` but MVP implementation may swap for semantic elements best suited for presentation

**Comment by tylerthome** [comment]
Related to issue #194 this should demonstrate a unified example of data access and global state management

**Comment by lola3736** [comment]
@tylerthome please review the complexity and points label for accuracy.
