### ISSUE TITLE
Progress bar as independent controlled component

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#237]
### Overview
Move the Progress Bar component into a dedicated ES6 module subscribing to context state

### Action Items
Render the progress bar based on the following pieces of information passed into its `props`:

- [ ] Current question index
- [ ] Ordered list of tuples: `<GroupName, NumQuestionsInGroup>`

### Resources/Instructions
Progress bar component should render itself with demarcated groups by name, and the progress indicator reflecting the index within its group

**Comment by tylerthome** [comment]
Closing this issues; this feature has been redesigned and this issue is no longer applicable for the module it was intended.

**Comment by lola3736** [comment]
@tylerthome Has this issue been replaced?
