### ISSUE TITLE
Host Application: Background check screen

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#241]
### Overview
We need to have a background check screen for the Host Application.

### Action Items
- [x] Product
   - [x] Gather requirements 
      - [x] Explanation of what Background Check is and why it is required
      - [x] Who in your household needs a Background check and why 
      - [x] External link to Background Check Vendor
      - [x] User confirms they submitted Background Check
   - [x] Discuss with Designers  
- [x] UI/UX
   - [x] Create Background Check Screen
- [ ] Development   
   - [ ] Define subtasks (Either in this issue or separate issues if there are multiple and link to this issue)

### Resources/Instructions
[Figma](https://www.figma.com/file/BJL6ZHfjrxVhU8jvD9gB3P/HomeUniteUs-Everything-Figma?node-id=1%3A1260)

**Comment by amimorga** [comment]
@gyanishere Any updates on this?

**Comment by gyanishere** [comment]
Yeah, I’ll update the shared figma and then mark it resolved.

**Comment by abbyhipp** [comment]
Development ok with but needs to be updated with new style guide when it is finished. Also need to consider who needs background checks.

**Comment by kpoints** [comment]
We've changed this workflow for MVP and will also be making new separate issues for development.
