### ISSUE TITLE
Create data access interface for Case

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#245]
### Overview
Create access methods for Case entity against MongoDB to enable our system to model case creation and updates

### Action Items

- [x] Define method: `create_case(case_worker_id, guest_id)`
- [x] Define method: `update_case_status(case_id, status_id)`
- [x] Define method: `reassign_case(case_id, case_worker_id)`

**Comment by tylerthome** [comment]
Closing this, as this data model has been specified and tracked as part of the Intake Profile module

**Comment by lola3736** [comment]
@tylerthome please review complexity label for accuracy.
