### ISSUE TITLE
Context support for client-side routing by question order

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#248]
### Overview
To enable registration question components to render the question view corresponding to their URL, define a mechanism by which the host dashboard context provider can be queried for question elements by their unique (but mutable) order ID

### Action Items

- [ ] Expose a data structure `hostQuestionsByOrderNum` or a callback `getHostQuestionByOrderNum` to supply a top-level questions by their `order` attribute
- [ ] (optional) specialize this structure or function into dedicated forms targeting `QualifyingQuestion` and `MatchingQuestion` explicitly

**Comment by tylerthome** [comment]
Per discussion on 10/3:

Initial MVP implementation will make minimal changes to existing design to support routing to and from the question page components.

* In the `clickForward` method of the question page components, edit the clause which advances the top-level question index such that it pushes a new location onto history .

* Set up a useEffect which watches the URL parameters and updates the top-level question index (i.e. `groupIndex`) in state accordingly.

Subsequent iterations will replace loop constructs with key-value lookups and optimize component hierarchy for reuse.

**Comment by tylerthome** [comment]
Per discussion on 10/6:

A parent component will perform the query of React Router's `useParams` hook and our custom `useHostDashboardData` hook to supply data to child views, selecting the proper view type based on the current question id.

To support the existing implementation of `MatchingQuestionPage`, the `HostDashboardDataProvider` will build an index for quick access to the `groupIndex` and `subgroupIndex` fields, possible using an ES6 Map

assuming
```
type QuestionId = string;
interface Grouping { 
    groupIndex: number; 
    subgroupIndex: number; 
};
```
context-level index might be structured as a
`Map<QuestionId, Grouping>`

**Comment by lola3736** [comment]
@tylerthome please review complexity and points label for accuracy.
