### ISSUE TITLE
Update guest matches detail page layout/style

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#25]
### Overview
Alex made mockups of how the admin/match page could look. Implement these on our match page to make it more presentable.

### Action Items

- [x] Review Alex's mockups in Figma
- [ ] Apply updates to tables

### Resources/Instructions
[Figma link](https://www.figma.com/file/Pc91SyV6Lu0D7kaw62FJLQ/SPY-Design-System)

**Comment by c-fuchs** [comment]
Per our meeting on 1/18, ETA is Sunday end of day 1/19
@tylerthome @KarlenS

**Comment by c-fuchs** [comment]
New change to implement: Let's pin the header row with column labels to the top. E.G. so that as an admin, I can scroll down through all a guest's matches while keeping the column labels in view so that I don't forget what the column represents.

**Comment by ExperimentsInHonesty** [comment]
@tylerthome is going to see about making the header row follow the scroll and @AlexChh93 is going to do the mocks ups for that.
