### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#258]
### Overview
We need the landing page to protect the current broken login by excluding it and give people who dont know anything about the project a place to get brief info and next contact steps

### Action Items
- [x] Redo landing page to have the following
   - [x] About text: https://docs.google.com/document/d/1FBbdIhupHfz9-Z3T6D94KStZTBN6xBsfBboJGBbLHsE/edit
   - [x] Partnership inquiries : Please reach out to homeuniteus@hackforla.org
   - [x] Help us develop the project: https://www.hackforla.org/projects/home-unite-us

### Resources
https://github.com/hackforla/home-unite-us-info

**Comment by ExperimentsInHonesty** [comment]
Page needs to be formatted attractively  and have the last check box addressed.

**Comment by ExperimentsInHonesty** [comment]
Next steps are figure out what needs to be on the landing page

**Comment by JRHutson** [comment]
Pinged @tylerthome on Slack to confirm if he got all he needs.

**Comment by JRHutson** [comment]
Added link to About Text written by Kristy and Bonnie above.

**Comment by JRHutson** [comment]
Reassigning to @tylerthome for implementation. Will be using default styling from Material UI at this point.

**Comment by JRHutson** [comment]
SSL Certificate is working properly. Current page looks like this. We have a separate ticket for the design team to create a layout that uses our design language, but I think this works until this is complete. Will review with PM team before closing.
<img width="698" alt="Screen Shot 2022-01-11 at 11 21 22 AM" src="https://user-images.githubusercontent.com/10876900/149007913-300b9c8e-8282-4e21-bb38-10d4409bdb1e.png">

**Comment by JRHutson** [comment]
Approved by Bonnie.
