### ISSUE TITLE
Coordinator Dashboard (Pilot)

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#261]
### Overview
We need to have a dashboard for the Coordinator to view.

### Action Items
- [x] Product
   - [x] Gather requirements 
      - [x] Case tracker(Applications): Status of guest and host applications and where they are in the system
      - [x] Case tracker(Post Applications): Status of guest and host and where they are in the system and how long they have been at each step (1)
      - [x] To do items with reminders for dependencies in workflow (2)
      - [x] List of matches, what coordinator is involved and what date the match expires(Will show all matches for pilot. May have some sorting functionality for future iterations). Will also show if one member of that match has some document expiring.
      - [x] List of hosts or guests that are not matched and if they have some document expiring (Ex. Insurance)
    - [x] Discuss with Designers  
- [ ] UI/UX
   - [ ] Create Dashboard screens
- [ ] Development   
   - [ ] Define subtasks (Either in this issue or separate issues if there are multiple and link to this issue)

### Questions
1: Do we want to show this?
2: Will calendaring show up on this list of to do items within the HUU dashboard

**Comment by abbyhipp** [comment]
![v2-overview](https://user-images.githubusercontent.com/69595646/106224709-aa98dc80-6198-11eb-9d5b-a1a1a9a2c28e.png)
<img width="1440" alt="v1-overview" src="https://user-images.githubusercontent.com/69595646/106224712-ac62a000-6198-11eb-898b-9eff482f1c9a.png">

**Comment by quyenvhle** [comment]
Duplicate with #284 , therefore close.
