### ISSUE TITLE
Local Provider Dashboard (Pilot)

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#262]
### Overview
We need to have a dashboard for the Local Provider where the Coordinators work to view information. This Local Provider perspective is to use this for marketing/funding and to understand where Coordinators need help or additional resources. 

### Action Items
- [ ] Product
   - [x] Gather requirements 
      - [x] Demographic data of Hosts and Guests
      - [x] Case tracker(Applications): Status of guest and host applications and where they are in the system (Overview)
      - [x] Case tracker(Post Applications): Status of guest and host and where they are in the system and how long they have been at each step 
      - [x] To do items: Overview of how many items outstanding for all Coordinators
      - [x] List of matches, what coordinator is involved and what date the match expires(Will show all matches for pilot. May have some sorting functionality for future iterations). Will also show if one member of that match has some document expiring.
      - [x] List of hosts or guests that are not matched and if they have some document expiring (Ex. Insurance)
    - [x] Discuss with Designers  
- [ ] UI/UX
   - [ ] Create Dashboard screens
- [ ] Development   
   - [ ] Define subtasks (Either in this issue or separate issues if there are multiple and link to this issue)

### Resources/Instructions

**Comment by quyenvhle** [comment]
Duplicate with #274 , therefore close.
