### ISSUE TITLE
Coordinator Dashboard: To do items

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#266]
### Overview
As a Coordinator I want a list of to do items so I know how to handle my workflow

### Action Items
- [ ] Product
   - [ ] Gather requirements 
      - [ ] List of applications that need approvals 
      - [ ] List of meetings that need confirmation that they occurred to push Host/Guest to next step
      - [ ] List of matches that need to be checked in on 
      - [ ] List of documents that need to be updated by Hosts/Guests (House insurance)
    - [ ] Discuss with Designers  
- [ ] UI/UX
   - [ ] Create Case Tracker Screen
- [ ] Development   
   - [ ] Define subtasks (Either in this issue or separate issues if there are multiple and link to this issue)

### Questions

**Comment by quyenvhle** [comment]
Feedback gathered from design critique 2/3: https://miro.com/app/board/o9J_lWYCfVY=/

**Comment by quyenvhle** [comment]
Duplicate with #284 , therefore close.
