### ISSUE TITLE
Coordinator Dashboard: Host/Guest matches screen

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#267]
### Overview
As a Coordinator I want a list of the host/guest matches, when they expire, which coordinator is in charge of them and if some of the host/guest documents are expiring

### Action Items
- [x] Product
   - [x] Gather requirements 
      - [ ] Show all host/guest matches with all cohosts/coguests also in the list
      - [ ] Expiration date of host/guest match 
      - [ ]  Coordinator associated with the match
      - [ ] Documents expiring for each member of the match. A symbol could be placed next to the match and when you click on the symbol it brings you to another screen to show you who has expiring documents
      - [ ] Place for coordinators to create notes to share with other coordinators about the matches if they need to let another coordinator handle their match (for example, if a specific host/guest has a specific allergy that needs consideration)
      - [ ] Terms and conditions to sign by the host and the guest( both might have different terms and conditions based on their role)(fairy)
      - [ ] Guest can give locality preference from the one's listed (fairy)
      - [ ] Feedback/survey form which will help us to improve the app(fairy)
    - [ ] Discuss with Designers  
- [ ] UI/UX
   - [ ] Create Case Tracker Screen
- [ ] Development   
   - [ ] Define subtasks (Either in this issue or separate issues if there are multiple and link to this issue)
- [ ] Database(fairy)
   - [ ] Define what database we will be using
   

### Questions
1. For Guests, should their profile be open for another match ~1 month before their current match ends to prevent them from not having a home?
2. When guest and host are all settled and are staying together, who should they reach out to incase there is an emergency or any urgent matters?(fairy)

**Comment by quyenvhle** [comment]
Duplicate with #284 , therefore close.
