### ISSUE TITLE
Audit Prototype: Desktop Dashboard

### ISSUE THREAD

**Issue by quyenvhle** [hackforla/HomeUniteUs#272]
### Overview
We need to audit 'Prototype: Desktop Dashboard' in order to create a coherent design system for HUU.

### Action Items
- [x] Meet with Julia to over audit process
- [x] Audit in progress
  - [x] Review existing screens
  - [x] Take notes of current styles (typography + color)
  - [x] Take notes of current styles (components - buttons & icons)
  - [x] List out proposed changes
- [x] Audit ready for review
- [x] Review with team
  - [x] Document feedbacks from team
- [x] Iterate based on feedback
- [x] Ready for design system

### Resources
Figma: https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=631%3A9689

**Comment by juliaa423** [comment]
Reviewed typography + colors in 2/17 design meeting. These are ready to be listed in design system. 
Will review components in Miro board and at next design meeting (3/3)

**Comment by juliaa423** [comment]
Components currently being added to design system
