### ISSUE TITLE
Increase ratio of image on hackforla.org project page for Home Unite Us to 3:2

### ISSUE THREAD

**Issue by shaswa** [hackforla/HomeUniteUs#275]
### Overview
All  project images on the [hackforla homepage projects section](https://www.hackforla.org/#projects) should have a 3:2 ratio and a standard resolution of 600x400 pixels or higher. 

Current Resolution: 1080 x 1080 pixels
Current Ratio: 1:1

### Action Items

- [x] Increase ratio of project image for Home Unite Us to 3:2
- [ ] Update Status on hackforla/website#1105
### Resources/Instructions
[Projects page](https://www.hackforla.org/#projects)
[Image](https://www.hackforla.org/assets/images/projects/home-heart.png)

**Comment by shaswa** [comment]
@abbyhipp  Could you provide an update for this?

**Comment by Oluwafemi-Jegede** [comment]
@abbyhipp 
Please provide updates

Progress:
Blockers:
Availability:
ETA:

**Comment by ExperimentsInHonesty** [comment]
Wrote to abby via slack today
```
Hi Abby.  This issue has been open for a while and its a quick fix.  Please assign it to one of the ui team members, or we will temporarily delist homeuniteus from the website: https://github.com/hackforla/HomeUniteUs/issues/275
```

**Comment by quyenvhle** [comment]
Sorry for the delay on our end. Attached is the updated image.[
![huu](https://user-images.githubusercontent.com/26660349/114799694-38cb3a80-9d66-11eb-8b08-78bdc1b653b3.png)
](url)
