### ISSUE TITLE
MVP Host Application

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#279]
### Overview
As a Host I want to submit an application to join the program so that I can help the homeless youth.

### Action Items
- [ ]  Review all comments labeled 279 on the MVP Hi Fi Host application screens 
(Comments 14-20 in the Figma board)
- [x] Update screens to reflect requests

Add in screens for:

- [ ] Background check (Refer to Gyan's archived page)

- [x] *Smoking/Drugs (Use Alcohol questions (copy/paste) format for these questions)
- [x] *Parent question "Are you willing to host a parent with a child"
- [x] *Animal question "Are you willing to host a guest with a pet"
- [x] *Co guest question "Are you willing to host more than one guest"

**Comment by quyenvhle** [comment]
#243

**Comment by fourmatte** [comment]
**Notes from 9-29 meeting:**

-Create remaining screens that are missing.

**Comment by JRHutson** [comment]
Farah completed updates. Moving into For Review.

**Comment by JRHutson** [comment]
Background check is dependent on external service.
