### ISSUE TITLE
MVP Guest Application

### ISSUE THREAD

**Issue by quyenvhle** [hackforla/HomeUniteUs#283]
### Overview
As a Guest, I want to submit my application to the program so that I can find a temporary place to stay

### Action Items
- [x]  Product
  - [ ] Gather requirements
- [x] Design
  - [x] Guest can fill out their application by answering questions
  - [x] Guest can save and quit their application
  - [x] Guest can see how much of the application they have completed (Example: Percentage of completion, etc.)
  - [x] Guest can upload photos of themselves

### Resources
- [List of questions](https://docs.google.com/spreadsheets/d/1QC2Kfd1J_r77IAXHgHrt-QCO3IIWI96MlEfvKWghBzA/edit#gid=0)
- [Host Application for design references](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=1230%3A3611)

**Comment by JRHutson** [comment]
Removing Role-Product Management label to avoid confusion. When things are ready for handoff to the dev team let's put them in the For Review column.

**Comment by kpoints** [comment]
Majority of these tasks have been completed. When figjam/board are finalized, will open new issue for developer to address.

**Comment by lola3736** [comment]
This issue has been replaced by [#533 Section 2 Guest Intake Profile (fka Application Form)](#533).
