### ISSUE TITLE
Coordinator dashboard: Design

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#284]
### Overview
As a Coordinator, I want to manage the applications, participants (Guest & Host), and matches of the Host Home Program.

### Action Items
- [ ] Design screens based on following requirements:
   - [x] Coordinator can view all applications submitted, categorized by Guest and Host and can click on the Guest/Host name to pull up their application/information in each stage they are in
   - [x] Coordinator has a text area to input information about each Host/Guest for explanation of why they are in certain stages or if extra explanation is required
   - [x] Coordinator can view which Guest/Host are in which states (stages)
       - [x] Stage 1: Application Received
       - [x] Stage 2: Application Approved
       - [x] Stage 3: Pre-match Meetings Completed
            - [x] Stage 3.1: Interview
            - [x] Stage 3.2: Training
       - [x] Stage 4: Host Selected by guest, Host is moved into a 'waiting zone' until they approve/deny the match
       - [x] Stage 5: Match Received, Host has approved the match
       - [x] Stage 6: Preliminary Meetings Completed
            - [x] Stage 6.1: Guest and Host meet at SPY
            - [x] Stage 6.2: Guest and Host meet at Hosts Home
       - [x] Stage 7: Match Finalized
       - [x] Stage 0: Holding Zone (Used for anyone the coordinator needs to move out of our current system: Respite, people on vacation etc)
   - [x] Coordinator can approve/deny applications
   - [x] Coordinator can move Guest/Host across states (stages)
   - [ ] Coordinator can link Guest with Co-guest
   - [x] Coordinator can match Guest with potential Hosts by using the HUU "Match" button which will use our automated system to match Guests and Hosts against the various qualifying questions
   - [ ] Coordinator can finalize the match (assigning one of the potential Hosts for the Guest)
   - [ ] Coordinator can revert the match and select status for guest/host (Create Hold/Unmatch button for post-matches that coordinator's can click at any time to rematch)
   - [x] Coordinator can add guests (Guests have to be added to the system, the coordinator will have a screen or pop up that allows them to add the guests email address. This will send an email to the guest inviting them to join HUU) - #295 

### Resources/Instructions
https://docs.google.com/presentation/d/1RhvqZfcLfyiokpuB9tGcR7oZ2zclDMaq9NT4NEckD1I/edit#slide=id.gc6803e55d3_0_0

**Comment by quyenvhle** [comment]
Please provide update 
1. Progress
2. Blocker
3. Availability
4. ETA

**Comment by JRHutson** [comment]
Bonnie requested that we display the date something is scheduled when the Host or Guest status indicated that they have a meeting scheduled. Ex. Interview Scheduled - 11/23/21
Tyler is researching how this will be done on the back end, but the design needs to have this integrated when we incorporate the updated status messages.

**Comment by kpoints** [comment]
The majority of these tasks have been completed or are already part of other existing issues. 

The following is being addressed in the Coordinator Dashboard workflows which will then be converted to issues:
```
 Coordinator can finalize the match (assigning one of the potential Hosts for the Guest)
 Coordinator can revert the match and select status for guest/host (Create Hold/Unmatch button for post-matches that coordinator's can click at any time to rematch)
```
The following has been converted into a new separate issue:

```
Coordinator can link Guest with Co-guest
```
