### ISSUE TITLE
Application Tracker Host & Application Tracker Guest: Development

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#290]
### Overview
As a developer, I want to understand the technical requirements for the Guest Application Tracker and Host Application Tracker.

### Action Items
- [ ] Review designs - #280
- [ ] Develop feature based on design and following requirements
  - Your Status 
      - Allow Guest/Host to view matched Guest/Host profile
      - Only display filled circle when Guest/Host complete a state 
      - Record date of completion of state and show in completed area
      - Show "In Progress" for state Guest/Host are in
      - If down arrow is pressed, drop down with information should appear
      - State management file ******
      - Pull name of state from State management file and display on screen in State management file designated order
      - Show progress bar (States completed/N) (See State management file for detailed explanation)
  - Action items section
      - Notify Host/Guest they need to make a meeting in Calendaring
      - Link Host/Guest to Calendaring
  - Coordinator section
      -  Link 'view profile' to coordinator profile
      - Display coordinators email/phone/name (information will come from SPY file)
  - Host section
      - Link 'view profile' to Host profile
      -  Display Hosts name
- [ ] Dependencies
  - [x] #299 
  - [x] #300 
  - [x] #301 

### Resources/Instructions
[MVP Host and Guest Application Tracker Figma
](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=1272%3A0)

### Questions

**Comment by tylerthome** [comment]
![image](https://user-images.githubusercontent.com/9952154/120082288-e96f6e00-c076-11eb-9329-cc6ee2819c7e.png)

**Comment by JRHutson** [comment]
Please provide update 
1. Progress
2. Blocker
3. Availability
4. ETA

**Comment by lasryariel** [comment]
- Legacy ticket, functionality has been redesigned and is being tracked in #455
