### ISSUE TITLE
Guest Sign Up/Coordinator Add Guest

### ISSUE THREAD

**Issue by quyenvhle** [hackforla/HomeUniteUs#295]
### Overview (WIP)
As a Coordinator, I want to only allow approved Guests to the program.
As a Guest, I want to sign up for an account so that I have a place to stay.

### Action Items
- [ ] Design screens based on the following requirements
   - [x] Coordinator can add a Guest to HUU by adding the Guest's email. (Coordinator dashboard)
   - [ ] Once the Guest's email is added, the Guest receives a unique sign in code. (Email/Happening outside of HUU)
   - [ ] The Guest can use their email + the unique sign in code to sign up for an account (Sign up flow) - #296 
   - [ ] Only Guest who successfully authenticate with their email and sign in code can begin the sign up process.

**Comment by lasryariel** [comment]
duplicate with #405 and #520
