### ISSUE TITLE
MVP Toolbar

### ISSUE THREAD

**Issue by quyenvhle** [hackforla/HomeUniteUs#297]
### Overview (WIP)
As a Coordinator/Guest/Host, I need a place where I can access important information.

### Action Items
- [x] Design screens based on the following requirements
    - [x] The toolbar is available on Guest/Host/Coordinator dashboard and consist of the following components:
      - [x] SPY Logo
      - [x] About Us (direct to markdown page on Github)
         - Intro about SPY
      - [x] Help (question mark)
         - Direct to SPY email
      - [x] Profile (picture icon) - internal profile that can only be seen by the user
        - Profile icon
        - First Name
        - Last Name
        - Email
        - Password change

**Comment by JRHutson** [comment]
Removing Role- Product Management Label. When ready to hand off to the dev team, let's place the issue in the For Review column to ensure the PM team knows to facilitate.

**Comment by lola3736** [comment]
This issue has been replaced by [#533 Section 2 Guest Intake Profile (fka Application Form)](#533).
