### ISSUE TITLE
ApplicationTracker: ActivityProgressView

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#300]
### Overview
React Component rendering an Activity's completed progress as a blue bar

### Action Items
Create a component that:
- [ ] accepts a containerWidth and an Activity
- [ ] renders a blue bar with full height and width = (actionsComplete / totalActions)%

### Resources/Instructions
Refer to issue #290

**Comment by lasryariel** [comment]
- Legacy ticket, functionality has been redesigned and is being tracked in #455
