### ISSUE TITLE
ApplicationTracker: ActivityListView

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#301]
### Overview
Component that renders a list of activities and whether they are complete.

### Action Items
Create a component that:
- [ ] accepts an Array<Activity> and callback functions for clicks within Actions
- [ ] renders an ActivityView for each Activity in the list
- [ ] renders a checkbox that where checked = dateCompleted < currentDate

### Resources/Instructions
Refer to issue #290 for more information

**Comment by lasryariel** [comment]
- Legacy ticket, functionality has been redesigned and is being tracked in #455
