### ISSUE TITLE
Coordinator profile(MVP)

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#303]
### Overview (WIP)
As a guest/host I want to get to know my coordinator through their profile

### Action Items
- [ ] Product
   - [ ] Gather requirements 
      - [ ] Profile will consist of
         - [ ] Name
         - [ ] Photos
         - [ ] About me section
    - [ ] Discuss with Designers  
- [ ] UI/UX
   - [ ] Create example profile screen for coordinators **and** screen for coordinator to input information into
- [ ] Development   
   - [ ] Define subtasks (Either in this issue or separate issues if there are multiple and link to this issue)

### Resources/Instructions
https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=4%3A2648

**Comment by rpbracker** [comment]
@kpoints This can be closed because only guests and hosts will have profiles.

**Comment by abiha1234** [comment]
Coordinator do not need profile in MVP and hence closing this out.
