### ISSUE TITLE
Guest/Host/Coordinator external profile

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#304]
### Overview
As a guest/host I want to get to know my host/guest through their profiles

### Action Items
- [x] Product
   - [x] Gather requirements 
      - Profile will consist of
         - Name
         - Photos
         - About me section
         - Notes from guest or host (Example: I have two cats)
    - [x] Discuss with Designers  
- [x] UI/UX
   - [x] Create example profile screen for guest/host. Please see current profile screen, we can use this format if you would like to.
- [x] Development   
   - [ ] Define subtasks (Either in this issue or separate issues if there are multiple and link to this issue)

### Resources/Instructions
https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=4%3A2648

**Comment by rpbracker** [comment]
This should probably be reconciled with issue #332

**Comment by kpoints** [comment]
The remaining tasks have been opened as new separate issues. 

Guest Profile 
https://github.com/hackforla/HomeUniteUs/issues/377

Host Profile
https://github.com/hackforla/HomeUniteUs/issues/378
