### ISSUE TITLE
MVP Application Technical Requirements

### ISSUE THREAD

**Issue by quyenvhle** [hackforla/HomeUniteUs#306]
### Overview
As a developer, I want to understand the technical requirements for the MVP Host and Guest Application

### Action Items
- [ ]  Product
   - [ ] Gather Requirements 
- [ ] Design
   - [ ] Complete Design
- [ ] Development
   - [ ] Gather Technical Requirements
      - [ ] Toolbar: Refer to MVP Toolbar ticket
        - [ ] Display toolbar in every page
      - [ ] Progress Bar
         - [ ] Progress bar should filled up based on the number of questions completed/ total number of questions
      - [ ] Questions
         - [ ] Display questions in the order as shown in prototype
         - [ ] User can not proceed without answering the question
         - [ ] When 'Back' button is clicked, direct user back to previous question with their answer pre-populated
         - [ ] When 'Save and Continue' button is clicked, save the answer and direct user to next question
         - [ ] Answers should be saved when user log out
         - [ ] Direct user to the last question that they saved when they log back in

### Resources/Instructions
[MVP Guest Application Figma
](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=1313%3A6673)
[MVP Host Application Figma
](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=1230%3A3611)

### Questions

**Comment by ExperimentsInHonesty** [comment]
Example of a technical requirements ticket.  Format later replaced by separate tickets for each practice area.
