### ISSUE TITLE
Add labels for issues 

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/HomeUniteUs#310]
### Overview
We need to identify the issue that are missing info so that we can get all issue properly classified.

### Action Items
- [x] Review each issue and add a missing label for each info item not present
   - [x] role
   - [x] milestone
   - [x] feature
   - [x] points

### Resources/Instructions
https://github.com/hackforla/HomeUniteUs/labels?q=missing

**Comment by eq2thex** [comment]
Missing labels added to everything on Kanban board that is missing role, milestone, feature, or points labels. Only exceptions were the 7/17 meeting recording listed under Done and the "Initial Spreadsheet for determining question schema and matching criteria," which was also listed under done (but not converted into an issue).

**Comment by eq2thex** [comment]
Last review and missing labels added on 12/6/21

**Comment by kpoints** [comment]
Rolled this into the [Weekly board Check](https://github.com/hackforla/HomeUniteUs/issues/354) as part of the [Weekly PM agenda](https://github.com/hackforla/HomeUniteUs/issues/364) issue.
