### ISSUE TITLE
Reformat and add new labels

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/HomeUniteUs#311]
### Overview
We need to have the labels be clear to everyone on the project and helpful to building and planning

### Action Items
- [x] edit role labels to be prepended with "role:"
- [x] edit the existing feature labels that are specific to user facing experience to be prepended with "p-feature:"
- [x] make a new label for feature that is invisible to the website user (tech debt, refactoring, administrative, etc.) [see example](https://github.com/hackforla/website/labels?q=feature%3A)
- [x] Make all point label (points: 1) use Fibonacci up to 8 and over 8 put points: 13+

### Resources/Instructions
See hackforla website for all their feature labels if needed: https://github.com/hackforla/website/labels
[Home Unite Us label page](https://github.com/hackforla/HomeUniteUs/labels)
[Home Unite Us current labels that start with "feature"](https://github.com/hackforla/HomeUniteUs/labels?q=feature)

**Comment by JRHutson** [comment]
Added and edited labels as described in tasks. Also, edited labels that had included (MVP) to match correct styling and made sure the issues were part of the MVP milestone. Created Milestone for New PM Onboarding and Cleanup to track this and other similar tasks.
