### ISSUE TITLE
Compile and Post Roles that need to be filled

### ISSUE THREAD

**Issue by JRHutson** [hackforla/HomeUniteUs#313]
### Overview
Define and fill team roles so we do not lose momentum

### Action Items 

- [x] Please comment with any roles that we should be looking to fill on the team through onboarding new members.
- [x] Do a write up job description for each open role
- [x] Post to Open roles board, 
- [x] Post to Out in Tech
- [x] Post to Catchafire volunteer roles

### Resources/Instructions
Open Role Boards
[Design](https://github.com/hackforla/UI-UX/projects/3) - design lead
[Research](https://github.com/hackforla/UI-UX/projects/2)
[Engineer](https://github.com/hackforla/engineering/projects/2)
[PM](https://github.com/hackforla/product-management/projects/8) - [draft PM focused on the Design](https://docs.google.com/document/d/1rt0bpGgpqtwyXl-IKSu-GdUiQtfrms93MHcD9gLRGNs/edit
[Ops](https://github.com/hackforla/ops/projects/1#column-12753343) - Put DBA here
)
[Data Science](https://github.com/hackforla/data-science/projects/2) later when we are ready with the types of data we will consult with Sophia and Ryan.

### Open roles currently posted
Engineering
[Front End Software Engineer](https://github.com/hackforla/engineering/projects/2#card-63202635)

**Comment by eq2thex** [comment]
Connect with Tracy, Calendaring Tech Lead
Tyler Thome, HUU Tech Lead
Alex Le, Design Tech Lead

**Comment by ExperimentsInHonesty** [comment]
We reference formal training above.  But to be clear, HackforLA is a do-ocracy, if you can do it, we don’t care how you learned.  You will find yourself in the company of all types of people, from the high school wizkid and PHDs to self taught high school dropouts, who have built and sold tech companies.  There is no one way to learn and we welcome your experience no matter how it was gained.  HackforLA is full of people driven to make a difference through civic tech. We look forward to your hearing how you will make a difference.

**Comment by quyenvhle** [comment]
Reviewed and provided comments for the Design PM role.

**Comment by JRHutson** [comment]
Posted Design Lead role to UI/UX board. Will try to join the UI/UX COP on weds to call attention to it.
