### ISSUE TITLE
Create slide deck for funding

### ISSUE THREAD

**Issue by quyenvhle** [hackforla/HomeUniteUs#317]
### Overview
We need a slide deck to raise funding for HUU.

### Action Items
- [x] Create initial slidedeck.
- [x] Get feedback from Bonnie and team on content.
- [x] Update slide deck based on Bonnie feedback.
- [x] Get design confirmation that the correct images are included 
- [x] Get feedback from design team on layout, styling, and images.
- [x] Update slide deck to reflect design feedback.
- [x] Get buy-in from Bonnie and team to finalize the deck.

### Resources/Instructions
[Slide Deck ](https://docs.google.com/presentation/d/1kLCQEyM-77LZvSpImQG8bWEL5KsHOgWdw67FRmiQ-Us/edit#slide=id.g1cf14567af1_0_118)

**Comment by quyenvhle** [comment]
Progress up to 8/2: 
- Updated slide deck to reflect Bonnie's comments on content.
- Added Key Challenges slide.

TBD: Update the remaining box design.

**Comment by quyenvhle** [comment]
Slide deck updated based on feedback from Bonnie.
https://docs.google.com/presentation/d/1KTRPdK6jeSXTmmwxDOYGUNtzzNCFIGv-wAbv-pI77VY/edit#slide=id.ge598db76fb_0_101

**Comment by JRHutson** [comment]
Moving back to Backlog since it is dependent on finalizing Figma designs.
