### ISSUE TITLE
Draft HUU Product Roadmap

### ISSUE THREAD

**Issue by eq2thex** [hackforla/HomeUniteUs#321]
### Overview
We need a product roadmap with product vision, roadmap, and series of release plans.

### Action Items

- [ ] Draft product roadmap
- [ ] Share draft with PM team to edit

### Resources/Instructions
[HfLA's roadmap guide - very out date](https://docs.google.com/document/d/1sZHHfqXoui4zsMQ2l_O3TRIJcXQnyOO-bF-KY9jl4qM/edit)

Examples of other project's roadmaps

- [Open Community Survey Roadmap](https://docs.google.com/spreadsheets/d/163RPNWPhkeah2OvGCqjByMukYduXk66XY7ZpcpLCzXU/edit#gid=617281993)
- [Guides Team Roadmap Example](https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0)
- Guides Team Milestones https://github.com/hackforla/guides/milestones

**Comment by eq2thex** [comment]
Bonnie suggested these roadmap examples from other projects as reference: 
https://docs.google.com/spreadsheets/d/163RPNWPhkeah2OvGCqjByMukYduXk66XY7ZpcpLCzXU/edit#gid=617281993
https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0
Milestone Guide: https://github.com/hackforla/guides/milestones

**Comment by lasryariel** [comment]
Our sections and milestones are our roadmap.
