### ISSUE TITLE
Repoint this dns to landing page

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/HomeUniteUs#327]
### Dependency
#258 

### Overview
We need to point the dns at the temp landing page so that people can see the appropriate content

### Action Items
- [ ] Point the about.homeunit.us to this repo
- [ ] make homeunite.us refresh to about.homunite.us

### Resources/Instructions
https://github.com/hackforla/home-unite-us-info

**Comment by JRHutson** [comment]
Homepage is back up. Moving to Backlog.

**Comment by tylerthome** [comment]
This item was completed shortly after it was created - we will address future DNS updates in separate issues
