### ISSUE TITLE
Create proto personas for guests, hosts, and coordinator

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#33]
### Overview
Our tool will be used by at least 3 main user groups. Create proto personas for guests, hosts, and coordinator.

### Action Items

- [ ] Create high-level, "proto" personas for
   - [x] Guests
   - [x] Hosts
   - [ ] Admins
- [x] Save these to the project in Figma 

### Resources
[Figma board](https://www.figma.com/file/Pc91SyV6Lu0D7kaw62FJLQ/SPY-Design-System?node-id=0%3A1)

**Comment by awadethomas** [comment]
Adding a link to the current version of proto-personas:
https://docs.google.com/document/d/1ZzPDxYRINMNFyuHXGRRSxPZM6quJOItmTf9xiTtz41E/edit

**Comment by awadethomas** [comment]
I have put initial versions of host and guest proto-personas together. I'll migrate them to a central board once we get permissions (see #34)
https://www.figma.com/file/OmB3MyXiCWyyLaMud8Lmud/User.Personas.IBD

A lot of the information was based on the following article that walks through the Host Home program at SPY: https://www.npr.org/2018/12/13/675369057/to-help-the-homeless-some-in-la-are-opening-their-doors-and-inviting-them-to-sta

**Comment by awadethomas** [comment]
Personas are now on the same board as the style guide:
https://www.figma.com/file/Pc91SyV6Lu0D7kaw62FJLQ/SPY-Design-System?node-id=278%3A8

We're holding off on working on the Admin persona until we have time to speak to or at least learn a bit more about the Admin, so this task is done minus Admin

**Comment by rpbracker** [comment]
@kpoints This can probably be closed out. We aren't doing admin profiles. Although it would be good to have the images for the guest / host profiles saved in a folder in the google drive somewhere in [this folder](https://drive.google.com/drive/u/1/folders/1FTCnoko-dfkWbFUeOlMQBFwQ_u24CD3t).

**Comment by kpoints** [comment]
Looks like these are tasks for a previous figma board. Will mark as closed and create new issues if we have specific personas/profiles we'll want for future demos/MVP.
