### ISSUE TITLE
Evaluate Auth0 UX Customization.

### ISSUE THREAD

**Issue by JRHutson** [hackforla/HomeUniteUs#334]
**UPDATE LABELS: Add the following labels to each new issue, and remove defaults:**
* Role
* Feature
* Points 
* Milestone

### Overview
Tyler needs to connect with the design team to show the options for customization in Auth0 so that we can identify how to best brand the login screen.

### Dependency
#196 

### Action Items
[ ] Finish reviewing Auth0 documentation
[ ] Identify designer who can connect
[ ] Schedule connection
[ ] Create design issues based on conversation.

**Comment by abiha1234** [comment]
We are moving away from Auth0 UX to Amazon Cognito, and hence closing this git issue now.
