### ISSUE TITLE
Project Page On Hackforla.org is out of date

### ISSUE THREAD

**Issue by JRHutson** [hackforla/HomeUniteUs#337]
### Overview
Need to update info for Hack For LA website and submit change request.

### Action Items

- [x] Identify which links should be on page and make sure they are active. (are we linking to a demo site, etc?)
- [x] Update the description
- [x] Update Project Team members
- [x] Update Frameworks
- [x] Add a link to the one sheet
- [x] After the information above is updated in the comment below, bonnie will help the team [open an issue on the hackforla.org website repo](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D)

### Resources/Instructions
- [https://www.hackforla.org/projects/home-unite-us](https://www.hackforla.org/projects/home-unite-us)
- Issue on Website team repo https://github.com/hackforla/website/issues/2715

**Comment by eq2thex** [comment]
Updated/edited. Here's the draft: [(https://docs.google.com/document/d/1FBbdIhupHfz9-Z3T6D94KStZTBN6xBsfBboJGBbLHsE/edit?usp=sharing)]

**Comment by ExperimentsInHonesty** [comment]
### Current Project Team

#### Add the following people
Name: Regan
Role: Product Management
Slack ID
GithHub Handle

Name: Surbi
Role: Product Management
Slack ID
GithHub Handle

Name: Eric
Role: 
Slack ID
GithHub Handle

#### Remove the following person
Name: Abby Hipp


### Modify Description
The Home Unite Us project is developing a workflow management tool for community non-profits to automate and scale their existing Host Home initiatives, prioritizing streamlining of caseworkers' repetitive workloads, reducing institutional bias, and effectively capturing crucial data.

Host Home programs are centered around housing young people, 18 - 25 years old. Their approach focuses on low-cost, community-driven intervention by matching a willing host with a guest or group of guests, providing a stable housing environment for youths who are experiencing homelessness and seeking stable housing.

**Comment by JRHutson** [comment]
@tylerthome Can you confirm if the Frameworks and Technologies listed on the project page are still relevant?

**Comment by JRHutson** [comment]
Tyler confirmed the current tools/Languages/Technologies should be:

Tools: Figma, AWS, Nginx, Docker, Style Components, Zoom, GitHub, Google Drive, Docs, Sheets, Slides

Languages: TypeScript, Python, JavaScript, Shell, Dockerfile, HTML

Technologies: React, NoSQL, Flask, Auth0 / OIDC / OAuth2, MongoDB

**Comment by JRHutson** [comment]
Summarizing Tool Updates:
Remove: Miro, Teraform, Dynamo DB,

**Comment by JRHutson** [comment]
Meeting Schedule Update:
Move Design Meeting to Tues 7:00-8:00PM every other Tuesday
Update Product Team Meeting to Tues 6:00-7:00 PM every week
Remove Weds Product Meeting

**Comment by JRHutson** [comment]
Opened issue for H4LA Website team to update. https://github.com/hackforla/website/issues/2715

**Comment by ExperimentsInHonesty** [comment]
I have prioritized the issue on the website repo.  Check back with me at next meeting.

**Comment by JRHutson** [comment]
No update yet on the Website team issue.
