### ISSUE TITLE
Coordinator Communication Log

### ISSUE THREAD

**Issue by JRHutson** [hackforla/HomeUniteUs#341]
### Overview
Coordinators need to be able to quickly identify Hosts and Guests that are holding up the process due by not completing a step. The communication log with let them quickly see the last milestone completed by a host or guest along with the date of completion.

### Action Items
Create Wireframe for interface to show the coordinator each participant's last action and when it was taken. Allow coordinator to quickly initiate an email to that user if there is something they need to do.

### Resources/Instructions
[Current Figma](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=1355%3A1)

**Comment by JRHutson** [comment]
Notes from 9-21 Meeting:
Comparison within matches is covered by the current matching interface. This should be a view of all hosts and guests a coordinator is working with.
Add UI elements for initiating an email to host or guest from the interface, sorting by date field and filtering to host/guests that have been flagged for inactivity.

**Comment by fourmatte** [comment]
**Notes from 9-28 Meeting:**
- Red flag alert should be time-sensitive. Define the timeframe (for action required by guest/host) for when red flag would 
be triggered on the communication log -- e.g. after 3 days, red flag appears in communication log under respective user, which requires a follow-up from coordinator.

**Comment by kpoints** [comment]
The work for this has been completed, will need to convert to 3 panel layout in https://github.com/hackforla/HomeUniteUs/issues/374.
