### ISSUE TITLE
Document Home Unite Us team meeting times and who Must/Should/Can attend

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/HomeUniteUs#342]
### Overview 
The Civic Tech Jobs team needs accurate meeting time information from the Home Unite Us team to help match your project with available volunteers.

### Action Items
- [x] provide details about the each meeting in a comment by using a copy of the check boxes below
- [ ] post a link to this issue on https://github.com/hackforla/CivicTechJobs/issues/35 in a comment letting the civic tech jobs team know you are done.
```
  - [ ] day
   - [ ] start_time
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min
   - [ ] name_of_meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
```
### Resources
- URL of the project's homepage on the HfLA website:  https://www.hackforla.org/projects/home-unite-us
- Times that VRMS shows for your meetings: 
Tue 7:00 pm, 1 hour
Sat 12:30 pm, 1.5 hour

**Comment by JRHutson** [comment]
@ExperimentsInHonesty I have a pending issue to update the meeting times on VRMS. Does that need to complete before I do this?

**Comment by ExperimentsInHonesty** [comment]
- [ ] day Tuesday
   - [ ] start_time 
      - [ ] AM
      - [x] PM
   - [ ] duration_in_min 60
   - [ ] name_of_meeting: Product Manager meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain

**Comment by ExperimentsInHonesty** [comment]
- [ ] day Tuesday
   - [ ] start_time 7
      - [ ] AM
      - [x] PM
   - [ ] duration_in_min: 60
   - [ ] name_of_meeting: All team meeting (every other Tuesday)
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain

**Comment by ExperimentsInHonesty** [comment]
- [x] day Tuesday
   - [x] start_time 7
      - [ ] AM
      - [x] PM
   - [x] duration_in_min: 60
   - [ ] name_of_meeting: Design (alternating Tuesday with All Team)
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain

**Comment by ExperimentsInHonesty** [comment]
- [ ] day: Friday
   - [ ] start_time 4:00
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min: 60
   - [ ] name_of_meeting: PM/Org
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
