### ISSUE TITLE
Onboard Rachel Bracker

### ISSUE THREAD

**Issue by JRHutson** [hackforla/HomeUniteUs#351]
###Overview

New Teammember Onboarding - Tasks to make sure new team-members have all needed resources and access

###Action Items:

#All Members:

- [x] Joined Github Org

- [x] Able to contribute on Home Unite Us Repo

- [x] Added to Slack channel #home-unite-us.

- [x] [Google Drive Access](https://drive.google.com/drive/u/0/folders/1ahxiD9rIsBtx0yAPlPcPaGw8zGrfHHm9)

- [x] Added to [Team Roster](https://docs.google.com/spreadsheets/d/1Qp0iLv5Bvafip9y8gu9AUy2d5800916ybJ4_YElmyYM/edit#gid=1806338047)

- [x] Reviewed [How Hack For LA Uses Kanban Guide](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit?usp=sharing)

- [x] Reviewed [Safe Place For Youth program overview](https://www.safeplaceforyouth.org/housing)

#UI/UX & Design:

- [x] Added to Slack channel #home-unite-us-design.

- [x] [Miro Access](https://miro.com/app/board/o9J_lSssM10=/)

- [x] [Figma Access](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=0%3A1)

- [x] Reviewed [Calendaring Figma] (https://www.figma.com/file/FrIY32ZqKGJxl3VQNoGgPg/Calendaring-Home-Unite-Us?node-id=140%3A410) for reference.

- [x] [Zeroheight Access](https://huu.zeroheight.com/login)

- [x] Connect with Design Lead for current status/priorities

**Comment by rpbracker** [comment]
I'm not sure why I am able to edit the HUU Everything Figma, since the sharing settings only say I can view it.

**Comment by rpbracker** [comment]
@JRHutson / @kpoints  -- only thing I don't have is Zeroheight access!
