### ISSUE TITLE
Get Contributors to Repo for Notification of License Update.

### ISSUE THREAD

**Issue by JRHutson** [hackforla/HomeUniteUs#363]
### Overview
Need to get a list of all contributors so they can be notified of the new license.

### Action Items

- [x] Pull list of all contributors to the repo from the Github API
- [x] Add list to this issue as a code block in a comment
- [x] Be sure to use a code block so we aren't spamming everyone with notifications until we want to

### Resources/Instructions
(Example Notification)
The Hack for LA organization is seeking to add the appropriate licenses to all projects. You are receiving this issue because you contributed code to our repository. If you disagree with the change to GNU GPL v2.0. Please let us know what pull request you submitted (provide a link to the pr in the comments of this issue), and we will remove the code.

We will apply the new license after June 1st 2022.

Resources

[GNU GPL v2.0](https://www.gnu.org/licenses/old-licenses/lgpl-2.0.html)

**Comment by JRHutson** [comment]
`@HassenH1
@arshiamasih
@tylerthome
@martyboggs
@erikguntner
@JRHutson
@timmalstead
@ExperimentsInHonesty
@c-fuchs
@MajorLift
@kkchu791
@AlbertUlysses
@kennethlee
@shubha-rajan
@eq2thex
tyler.thome@outlook.com
timmmalstead@gmail.com
karlen.shahinyan@mindmics.com
dsi@macbook-pro.local
kirkchu@merqbizdminsmbp.lan`

**Comment by JRHutson** [comment]
@rossbb @kpoints I think this is ready to post. The only question is how long we give for people to respond before we implement the license. Does setting a June 1st deadline seem reasonable?

**Comment by rossbb** [comment]
@JRHutson Can we close this issue?

**Comment by JRHutson** [comment]
@rossbb Yes. Closing. I thought it had been.
