### ISSUE TITLE
Home Unite Us Google Drive Folder Migration

### ISSUE THREAD

**Issue by kpoints** [hackforla/HomeUniteUs#365]
### Overview
Migrate all previous files from the previous [Home Unite Us](https://drive.google.com/drive/folders/1ahxiD9rIsBtx0yAPlPcPaGw8zGrfHHm9?usp=sharing) folder to the new Home Unite Us Shared drive.

### Action Items
- [x] Set up free calendly with times that Bonnie will make available (Note: each block is 30min and can do 2 appointments per half hour)
- [x] Let bonnie know after you have setup calendly with a test date, and you have your draft of the email she is going to send, then she will give you up to date dates for the following two weeks.
      Monday 2/7 2:00pm
      Monday 2/7 3:00pm
      Wednesday 2/9 1:00pm 
      Wednesday 2/9 2:00pm
      Thursday 2/10 1:00pm
      Thursday 2/10 2:00pm
      Friday 2/11 12:00pm
      Friday 2/11 2:00pm
      Monday 2/14 2:00pm
      Monday 2/14 3:00pm
      Wednesday 2/16 1:00pm
      Wednesday 2/16 2:00pm
      Wednesday 2/16 3:00pm

- [x] Create issue and assign to Bonnie 
- [x] Generate a draft of the wording for emails that Bonnie can send out to the list. Including the following topics:
   - Hey, need your help moving some files 
   - Would love to catch up with you
   - Calendly information
   
Team Members to reach out to:
- [x] Chhuon, Alex
- [x] Chu, Kirk
- [x] Curtin, H-L
- [x] Fuchs, Carolanne
- [x] Henderson, Joel Parker
- [x] Hipp, Abby
- [x] Le, Alex
- [x] Michelle, Tracy
- [x] Shahinyan, Karlen
- [x] Thomas, Aaron

### Resources/Instructions
[Folder Migration Audit spreadsheet](https://docs.google.com/spreadsheets/d/1zUxMCRICcOgLX4EWPqX_We6ye-7VGn-aYVVUAr-TKE4/edit#gid=0)
[Email Draft](https://docs.google.com/document/d/1CQyvtUbE6i-0UOziID5sSNu8H49Zitoo2lvGZzSHoLY/edit)
[Calendly Scheduling](https://calendly.com/homeuniteus/30-minute-meeting)

**Comment by rsschacht** [comment]
Hey @kpoints @JRHutson , Calendly wants me to authorize homeuniteus@hackforla.org via Google sign up. This requires the Google password, and I'm only on a forwarding email for this (so I don't know it). 

We can take either of the following actions here:

1. Sign up with Google, in which case I will need someone to provide me with the current password 
2. Create an alternative password that is specific to Calendly. I can use a random strong password generator, but we'll need to figure out where it lives in our team so that Bonnie and others can log in when needed and access it easily.

Thanks!

**Comment by ExperimentsInHonesty** [comment]
@rsschacht reassign me when you are ready.  I added  your details to the email address (email and phone) so you should be able to log into the account now.

**Comment by rsschacht** [comment]
Thank you @ExperimentsInHonesty , it's done:
Calendly: https://calendly.com/homeuniteus/30-minute-meeting 
Template draft: https://docs.google.com/document/d/1CQyvtUbE6i-0UOziID5sSNu8H49Zitoo2lvGZzSHoLY/edit?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
I will reach out to 
Chu, Kirk
 Fuchs, Carolanne
 Henderson, Joel Parker
 Hipp, Abby
 Le, Alex
 Shahinyan, Karlen

**Comment by rsschacht** [comment]
Collected emails for outreach: 

- [ ] Alex Chhuon: [ChhuonAlex@gmail.com](mailto:ChhuonAlex@gmail.com)
- [ ] Kirk Chu: [kkchu791@gmail.com](mailto:kkchu791@gmail.com)
- [ ] H-L Curtin: [larkcurtin@gmail.com](mailto:larkcurtin@gmail.com)
- [ ] Carolanne Fuchs: [carolanne.fuchs@gmail.com](mailto:carolanne.fuchs@gmail.com)
- [ ] Joel Parker Henderson: [joel@joelparkerhenderson.com](mailto:joel@joelparkerhenderson.com)
- [ ] Abby Hipp: [tnahipp@gmail.com](mailto:tnahipp@gmail.com)
- [ ] Alex Le: [quyenvhle@gmail.com](mailto:quyenvhle@gmail.com)
- [ ] Tracy Michelle: [sunnyskies0333@gmail.com](mailto:sunnyskies0333@gmail.com)
- [ ] Karlen Shahinyan: [shkarlen@gmail.com](mailto:shkarlen@gmail.com)
- [ ] Aaron Thomas: [aaronthomasxd@gmail.com](mailto:aaronthomasxd@gmail.com)

**Comment by rsschacht** [comment]
As of 3/2/22, all outreach sent: 

- [ ] Alex Chhuon: [ChhuonAlex@gmail.com](mailto:ChhuonAlex@gmail.com)
- [ ] Kirk Chu: [kkchu791@gmail.com](mailto:kkchu791@gmail.com)
- [ ] H-L Curtin: [larkcurtin@gmail.com](mailto:larkcurtin@gmail.com)
- [ ] Carolanne Fuchs: [carolanne.fuchs@gmail.com](mailto:carolanne.fuchs@gmail.com)
- [ ] Joel Parker Henderson: [joel@joelparkerhenderson.com](mailto:joel@joelparkerhenderson.com)
- [ ] Abby Hipp: [tnahipp@gmail.com](mailto:tnahipp@gmail.com)
- [ ] Alex Le: [quyenvhle@gmail.com](mailto:quyenvhle@gmail.com)
- [ ] Tracy Michelle: [sunnyskies0333@gmail.com](mailto:sunnyskies0333@gmail.com)
- [ ] Karlen Shahinyan: [shkarlen@gmail.com](mailto:shkarlen@gmail.com)
- [ ] Aaron Thomas: [aaronthomasxd@gmail.com](mailto:aaronthomasxd@gmail.com)

Confirmed:
- [ ] Alex Chhuon: [ChhuonAlex@gmail.com](mailto:ChhuonAlex@gmail.com)
- [ ] Kirk Chu: [kkchu791@gmail.com](mailto:kkchu791@gmail.com)
- [ ] H-L Curtin: [larkcurtin@gmail.com](mailto:larkcurtin@gmail.com)
- [ ] Carolanne Fuchs: [carolanne.fuchs@gmail.com](mailto:carolanne.fuchs@gmail.com)
- [ ] Joel Parker Henderson: [joel@joelparkerhenderson.com](mailto:joel@joelparkerhenderson.com)
- [ ] Abby Hipp: [tnahipp@gmail.com](mailto:tnahipp@gmail.com)
- [ ] Alex Le: [quyenvhle@gmail.com](mailto:quyenvhle@gmail.com)
- [ ] Tracy Michelle: [sunnyskies0333@gmail.com](mailto:sunnyskies0333@gmail.com)
- [ ] Karlen Shahinyan: [shkarlen@gmail.com](mailto:shkarlen@gmail.com)
- [ ] Aaron Thomas: [aaronthomasxd@gmail.com](mailto:aaronthomasxd@gmail.com)
