### ISSUE TITLE
Figjam - Coordinator User flow

### ISSUE THREAD

**Issue by abiha1234** [hackforla/HomeUniteUs#367]
### Overview
Outline coordinator user flow in figjam.

### Action Items

- [x] Review coordinator user stories
- [x] Create the initial coordinator user flow figjam 
- [x] Review coordinator user flow with the team

### Resources/Instructions
[Link to figjam](https://www.figma.com/file/5umaDiU1AM4oygqiLs7f33/Workflow?node-id=0%3A1)
[Link to HUU User stories](https://docs.google.com/spreadsheets/d/1MGemlk3PTSlg3OaKZ7QYLseE4GWqcgqx1C5HeHxUwR8/edit#gid=1915738987)

**Comment by JRHutson** [comment]
@abiha1234 
Please provide update 
1. Progress
2. Blocker
3. Availability
4. ETA

**Comment by JRHutson** [comment]
Reviewed with @abiha1234. Reassigned to myself for final review with UI/UX and Dev teams.

**Comment by JRHutson** [comment]
@rpbracker Coordinator Figjam.

**Comment by JRHutson** [comment]
Complete.
