### ISSUE TITLE
Onboard Utkarsh Saboo

### ISSUE THREAD

**Issue by JRHutson** [hackforla/HomeUniteUs#371]
###Overview

New Teammember Onboarding - Tasks to make sure new team-members have all needed resources and access

###Action Items:

#All Members:

- [ ] Joined Github Org

- [ ] Able to contribute on Home Unite Us Repo

- [x] Added to Slack channel #home-unite-us.

- [ ] [Google Drive Access](https://drive.google.com/drive/u/0/folders/1ahxiD9rIsBtx0yAPlPcPaGw8zGrfHHm9)

- [ ] Added to [Team Roster](https://docs.google.com/spreadsheets/d/1Qp0iLv5Bvafip9y8gu9AUy2d5800916ybJ4_YElmyYM/edit#gid=1806338047)

- [ ] Reviewed [How Hack For LA Uses Kanban Guide](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit?usp=sharing)

- [ ] Reviewed [Safe Place For Youth program overview](https://www.safeplaceforyouth.org/housing)

#Developers:

- [x] Added to Slack channel #home-unite-us-dev.

- [ ] [Environment Setup](https://github.com/hackforla/HomeUniteUs#readme)

- [ ] Connect with Dev Lead for current status/priorities

###Resources/Instructions

PM Facilitating Onboarding will create an issue for each new member. Once the member has Github access, re-assign the issue to them for tracking completion.

**Comment by JRHutson** [comment]
@usaboo attended onboarding last night 2/7. Reassigning to them to complete onboarding.

**Comment by tylerthome** [comment]
Utkarsh is going to start with the Hack for LA website team after his initial onboarding, and hopes to join HUU in the near future. I recommend closing this ticket for now as he will not be joining the project at this time.
