### ISSUE TITLE
Coordinator Communication Log - 3 Panel Layout

### ISSUE THREAD

**Issue by kpoints** [hackforla/HomeUniteUs#374]
### Overview
We want to standardize the layout of the coordinator communication dashboard to the 3 panel layout in the figma board. 

### Action Items
- [ ] Review existing Coordinator communication log in the coordinator dashboard
- [ ] Update layout from existing layout to the 3 panel layout
- [ ] Request a review during a design or all team meeting

### Resources/Instructions
Original work done in https://github.com/hackforla/HomeUniteUs/issues/341

**Comment by fourmatte** [comment]
Implementing the three panel layout on guest and host trackers first. need some clarity on coordinator dashboard specs to keep overall design consistent across all screens.

https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Jan2022?node-id=1467%3A16011

**Comment by lasryariel** [comment]
Legacy ticket, design has gone in a different direction.
