### ISSUE TITLE
Figjam - Host & Guest User flow

### ISSUE THREAD

**Issue by abiha1234** [hackforla/HomeUniteUs#376]
### Overview
Outline Host & Guest user flow in figjam.

### Action Items

- [ ] Create the initial Host and Guest user flow figjam - Completed guest, need to work on host
- [ ] Review host and guest user flow with the team

### Resources/Instructions
[Link to figjam](https://www.figma.com/file/rCf4YJufx7r2EyPR4hhNen/Host-%26-Guest?node-id=0%3A1)
[Link to HUU User stories](https://docs.google.com/spreadsheets/d/1MGemlk3PTSlg3OaKZ7QYLseE4GWqcgqx1C5HeHxUwR8/edit#gid=1915738987)

**Comment by JRHutson** [comment]
Need to finish Guest flow and review with team.

**Comment by JRHutson** [comment]
@rpbracker Here's the task for the Host and Guest fig jams.

**Comment by lasryariel** [comment]
Updated user flows exist here: https://www.figma.com/design/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?node-id=4766-43901&t=oLH5oYevFIwiEsIg-0
