### ISSUE TITLE
Host External Profile - 3 Panel Layout

### ISSUE THREAD

**Issue by kpoints** [hackforla/HomeUniteUs#378]
### Overview
We want to revise the existing layout of the profile view to the new 3-panel layout to keep the user experience consistent for developers to implement and reduce user education and support requirements 

### Action Items
- [ ] Review existing profile view in the Host dashboard
- [ ] Update layout from existing layout to the 3 panel layout
- [ ] Request a review during a design or all team meeting

### Resources/Instructions
Original work done in https://github.com/hackforla/HomeUniteUs/issues/304 and https://github.com/hackforla/HomeUniteUs/issues/332

**Comment by rpbracker** [comment]
@itzflowa  --- This definitely is a thing that needs to get done eventually, but I would want to confer with the PMs over how much of a priority it should be.

**Comment by lasryariel** [comment]
Figma link in original issue goes nowhere. Closing this as unplanned.
