### ISSUE TITLE
Design and implement initial state machine database model for all business entities

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#391]
### Overview
Define the base schema(s) to be used for stateful entities in the HUU logical business model

### Action Items
- [ ] Create a state machine or statechart for the `Case` model

### Resources/Instructions
* Example basic statechart information for `Case`:
  * states:
    * awaiting_coordinator_approval
    * awaiting_host_acceptance
    * awaiting_initial_meeting
    * ineligible
  * events
    * guest_submit_interest
    * guest_withdraw_interest
    * coordinator_approve
    * coordinator_reject
    * coordinator_create_case
    * host_accept
    * host_reject
* Reference material:
  * For design, consider the `Trip` model in [this article](https://eng.uber.com/sessionizing-data/)
  * For implementation, consider the "Programming Model" section of [this article](https://eng.uber.com/fulfillment-platform-rearchitecture/)
  * Conceptual and technical
    * https://xstate.js.org/docs/guides/introduction-to-state-machines-and-statecharts
    * https://statecharts.dev/
    * https://en.wikipedia.org/wiki/Finite-state_machine

**Comment by tylerthome** [comment]
An important requirement to bear in mind for this task is that we will need two sets of dynamic state types that will vary by organization:
* Document submittals
* Trainings / orientations

For the initial pass at the state machine or statechart, consider these as aggregate states e.g. `awaiting_all_documents_submitted` and `awaiting_all_trainings_completed` (feel free to change the naming convention, another alternative for these examples could be `host_submitting_documents` and `host_completing_trainings`  or any that clearly represent the state)

**Comment by tylerthome** [comment]
As part of the existing work underway for the basic features, this requirement will be satisfied using the PostgreSQL transaction log directly, or an integration with e.g. [RedHat's Debezium](https://debezium.io/documentation/reference/2.6/connectors/postgresql.html)

**Comment by tylerthome** [comment]
Design has been established and future work specification is underway

**Comment by lola3736** [comment]
@tylerthome please review the complexity label for accuracy.
