### ISSUE TITLE
Update Project License

### ISSUE THREAD

**Issue by JRHutson** [hackforla/HomeUniteUs#408]
### Overview
Project needs a License.

### Action Items

- [x] Update Project license to  GNU GPL v2.0.

### Resources/Instructions
Contributors were informed by #406

**Comment by rossbb** [comment]
@JRHutson @tylerthome Can this issue be closed?

**Comment by JRHutson** [comment]
<img width="190" alt="Screen Shot 2022-09-26 at 5 35 58 PM" src="https://user-images.githubusercontent.com/10876900/192405078-855d2a0e-18bd-4ff3-b782-38b3d1fc158f.png">
Yes. The license was updated.
