### ISSUE TITLE
PRD - Guest Application Dashboard

### ISSUE THREAD

**Issue by rossbb** [hackforla/HomeUniteUs#415]
### Overview
Create a Product Requirements Document for the Guest Dashboard that clearly lays out all requirements, included features, and expected functionality in a way that provides design and engineering the information they need to bring the feature/view to life.

### Action Items
[ ] Create PRD following HUU's PRD Template
[ ] Submit PRD for Review & Approval
[ ] Complete any requested Edits
[ ] Present and Review PRD with Design & Engineering 
[ ] Make any necessary adjustment
[ ] Add 'completed' PRD to project documentation

Please note the all PRDs are living documents and will need to be updated/revised throughout the implementation process!

### Resources/Instructions
Start by creating a copy of the HUU PRD Template: :https://docs.google.com/document/d/1g_orDIFkiNOZMkk79GVdn15xAsmEsN3oHqtGum1Id5s/edit#heading=h.kni59zaoyn23

**Comment by JRHutson** [comment]
Based on discussions, moving to Out Of Scope category. Determined that there is not significant value to a guest dashboard.

**Comment by JRHutson** [comment]
Not planning to implement.

**Comment by JRHutson** [comment]
Trying again.

**Comment by lola3736** [comment]
This issue has been replaced by [Section 2 Guest Intake Profile (fka Application Form)](#533)
