### ISSUE TITLE
PRD - Guest App Settings

### ISSUE THREAD

**Issue by rossbb** [hackforla/HomeUniteUs#418]
### Overview
Create a Product Requirements Document for the Guest Application Setting view that clearly lays out all requirements, included features, and expected functionality in a way that provides design and engineering the information they need to bring the feature/view to life.

### Action Items
[ ✓] Create PRD following HUU's PRD Template
[ ✓] Submit PRD for Review & Approval
[ ✓] Complete any requested Edits
[ ] Present and Review PRD with Design & Engineering 
[ ] Make any necessary adjustment
[ ] Add 'completed' PRD to project documentation

Please note the all PRDs are living documents and will need to be updated/revised throughout the implementation process!

### Resources/Instructions
https://docs.google.com/document/d/15GAXOFpav5NyicUxqQbzNFGAB52JPG_ZRGpy9_n4MiM/edit

### Related Issues:
#429

**Comment by lasryariel** [comment]
The document has been initiated. Marking this complete.
