### ISSUE TITLE
PRD - Guest Profile/Application

### ISSUE THREAD

**Issue by rossbb** [hackforla/HomeUniteUs#419]
### Overview
Create a Product Requirements Document for the Guest Profile/Application that clearly lays out all requirements, included features, and expected functionality in a way that provides design and engineering the information they need to bring the feature/view to life.

### Action Items
- [x] Create PRD following HUU's PRD Template
-- [Guest Profile PRD](https://docs.google.com/document/d/1ob9edR8yH3z26tbqODVKk9MjsdEi83W4xprPZCDKj_k/edit#heading=h.6z2m6swu5yfk)
- [ ] Submit PRD for Review & Approval
- [ ] Complete any requested Edits
- [ ] Present and Review PRD with Design & Engineering 
- [ ] Make any necessary adjustment
- [ ] Add 'completed' PRD to project documentation

Please note the all PRDs are living documents and will need to be updated/revised throughout the implementation process!

### Resources/Instructions
Start by creating a copy of the HUU PRD Template: :https://docs.google.com/document/d/1g_orDIFkiNOZMkk79GVdn15xAsmEsN3oHqtGum1Id5s/edit#heading=h.kni59zaoyn23

**Comment by rossbb** [comment]
Guest Profile PRD:
https://docs.google.com/document/d/1ob9edR8yH3z26tbqODVKk9MjsdEi83W4xprPZCDKj_k/edit#heading=h.6z2m6swu5yfk

**Comment by lola3736** [comment]
This is issue is no longer needed given the current built.  Note: Issue was created by legacy PM, who is no longer needed.
