### ISSUE TITLE
Create Tickets Based on Master Stories List

### ISSUE THREAD

**Issue by rossbb** [hackforla/HomeUniteUs#429]
### Overview
Create Github tickets based on the projects [Master Stories](https://docs.google.com/document/d/1633cnk9ZnuUbbYv8psokNkSUiAXHpbvxi4tbLGPLnQY/edit#) List

### Action Items

- [ ] Create Tickets for each Major Feature
- [ ] Create Master/Epic Tickets for each Major Interface
- [ ] Create Tickets as needed for each user story

### Resources/Instructions
[Project Wiki](https://github.com/hackforla/HomeUniteUs/wiki/Product-Requirements-&-Documentation)

**Comment by K-Gumarama** [comment]
Added ticket #431  to correspond under Guest Interface - Manage Account Information. Currently in New Issue Approval

**Comment by K-Gumarama** [comment]
Added tickets #432 and #433 under Major Feature - Messaging. I created a ticket for the Guest interface and Host interface.
