### ISSUE TITLE
Review and Clean Up Feature Labels

### ISSUE THREAD

**Issue by JRHutson** [hackforla/HomeUniteUs#430]
### Overview
Review and clean up feature labels on the Github board.
Use current list of features on the [Master User Stories](https://docs.google.com/document/d/1633cnk9ZnuUbbYv8psokNkSUiAXHpbvxi4tbLGPLnQY/edit?usp=sharing) document for reference.
Currently feature labels are prefaced with either "Feature" or "p-Feature".
p-Feature was used to call out features that were end user facing.

### Action Items

- [ ] Review Feature List from User Stories document
- [ ] Remove Feature labels for features that are no longer relevant
- [ ] Add Feature labels for any that do not have a label

### Resources/Instructions
[Project Wiki](https://github.com/hackforla/HomeUniteUs/wiki/Product-Requirements-&-Documentation)

**Comment by lasryariel** [comment]
feature label are fine for now. when new features are added we will update.
