### ISSUE TITLE
Home Unite Us Email Template

### ISSUE THREAD

**Issue by brycelednar** [hackforla/HomeUniteUs#458]
#### The Problem:

Currently, there is no standardized design for automated emails sent from the Home Unite Us app, including emails to complete sensitive functions (e.g., reset password, confirm account). As a result, users may not trust these automated emails or complete the intended user flows.

#### Objective:

Create a template for automated emails sent from the Home Unite Us app. 

#### Acceptance Criteria:

* Includes Home Unite Us branding and aligns with the HUU design system
* Includes a link to the Home Unite Us homepage
* Compatible with varying lengths of copy
* Compatible across mobile, desktop, and tablet

Figma link https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?type=design&node-id=2353-17358&mode=design&t=JaCBzex1h0ZqN3oa-0

**Comment by IndigoYinZ** [comment]
<img width="1303" alt="Frame 2" src="https://user-images.githubusercontent.com/121915931/231320512-15bde831-33a3-42b2-b9e1-c8321b08afaf.png">
<img width="1350" alt="Frame 1" src="https://user-images.githubusercontent.com/121915931/231320516-7c28b8f3-5710-4c1a-8340-c4a945a15f2b.png">

**Comment by yin** [comment]
@brycelednar not me...

**Comment by brycelednar** [comment]
Thanks again for all of your work on this, @IndigoYinZ! 

Hi @erikguntner, the Figma for the email templates is [here](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?type=design&node-id=2353-17358&mode=design&t=JaCBzex1h0ZqN3oa-0) . 

Is there anything else that you need for the email template? 

Any content that we don't have can be left out from the template (like phone, address)

**Comment by erikguntner** [comment]
@brycelednar I noticed two things. The reset password email should include a code instead of a link, and the verification email design currently includes the person's name. We aren't collecting names for hosts and coordinators at sign up, so we won't be able to use the name in the verification email. 

I'll make some updates and let me know what you think.

**Comment by brycelednar** [comment]
Got it, @erikguntner. Just to clarify, the content in the body of the email template here is just a placeholder, the goal for this issue is to provide a template in HUU styling that can be used for any emails sent from the HUU app.

**Comment by erikguntner** [comment]
Ahh gotcha. As a design template this looks good to me.

**Comment by brycelednar** [comment]
Thanks @erikguntner, I'll close this issue out.
