### ISSUE TITLE
Create User and Applicant Models

### ISSUE THREAD

**Issue by erikguntner** [hackforla/HomeUniteUs#462]
### Overview
Create SQLAlchemy models for user and applicant models in accordance with the attached data model schematic.

### Action Items
- Create models with deserializers for the user and applicant tables

Are there any other properties we want to attach to the user table aside from the email?  Do we want add a Cognito Id?

### Resources/Instructions
![HomeUniteUs_ERD_20230117 drawio](https://user-images.githubusercontent.com/27253583/220491081-9e4fefbc-08d3-4478-9955-218d30ee96cd.png)

**Comment by tylerthome** [comment]
This feature will be completed concurrent with tracked intake profile development work

**Comment by ExperimentsInHonesty** [comment]
I am moving this issue back to the new issue approval column, because the previous assignees are marked as[ inactive on the roster](https://docs.google.com/spreadsheets/d/1Qp0iLv5Bvafip9y8gu9AUy2d5800916ybJ4_YElmyYM/edit#gid=1609056339).
