### ISSUE TITLE
Add server-side validation

### ISSUE THREAD

**Issue by erikguntner** [hackforla/HomeUniteUs#478]
### Overview
Although we are handling validation on the frontend, we still need to validate our data on the server. I'm unsure if Flask or connexion provide server validation functionality, but I think that should be the first place we look before exploring other libraries.

### Action Items
- Decide on a server-side validation strategy for incoming requests
- Update the necessary endpoints

[Connexion docs](https://connexion.readthedocs.io/en/latest/)
[Flask docs](https://flask.palletsprojects.com/en/2.2.x/)

**Comment by paulespinosa** [comment]
connexion might be doing validation automatically based on the OpenAPI spec: 
https://github.com/spec-first/connexion/blob/main/ARCHITECTURE.rst

Need to confirm...

**Comment by brycelednar** [comment]
Hi @erikguntner, can you add a points estimate label to this issue? I'm doing so board clean up. Thanks!

**Comment by erikguntner** [comment]
@brycelednar I think Paul is right and this is handled automatically by the library we are using. I'm going to close this issue for now.
