### ISSUE TITLE
End point to reset password when guest signs  in after invite

### ISSUE THREAD

**Issue by erikguntner** [hackforla/HomeUniteUs#480]
### Overview
When a guest receives an invitation to sign up for Home Unite Us they are instructed to click on a link that redirects them to a page to create a permanent password. We need an endpoint in our API that handles resetting the password. If I understand [the flow](https://docs.aws.amazon.com/cognito/latest/developerguide/how-to-create-user-accounts.html) correctly, after a user is invited they must respond the the auth challenge set by Cognito to reset their password, which can be done using the [RespondToAuthChallenge](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp/client/respond_to_auth_challenge.html) method.

### Action Items
- Create OpenAPI spec for a POST endpoint that accepts a password in the body.
- Generate a new spec
- Return an error if the request is unsuccessful

### Resources
[Invite user flow](https://docs.aws.amazon.com/cognito/latest/developerguide/how-to-create-user-accounts.html)
[RespondToAuthChallenge](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp/client/respond_to_auth_challenge.html)

**Comment by erikguntner** [comment]
@jed-stewart can you confirm that after sending the invite the user has a RESET_REQUIRED or FORCE_CHANGE_PASSWORD status?

**Comment by jed-stewart** [comment]
Yes, I'll verify this

**Comment by jed-stewart** [comment]
> @jed-stewart can you confirm that after sending the invite the user has a RESET_REQUIRED or FORCE_CHANGE_PASSWORD status?

@erikguntner @stevbark It is FORCE_CHANGE_PASSWORD when added

**Comment by stevbark** [comment]
Is the FORCE_CHANGE_PASSWORD something I need to worry about? I dont see it in the 'respond to auth challenge' linked above so I am unsure how it affects me.
