### ISSUE TITLE
Document Possible Values for User Status

### ISSUE THREAD

**Issue by randelbrot** [hackforla/HomeUniteUs#489]
### Overview
Align on possible values for user status, including status definitions so that ????

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions

- Draft: [User Status document](https://docs.google.com/document/d/1mksBNqE9hc-bAW49mdHQDImkk8f92YewtwENNpqvFHc/edit)

**Comment by lasryariel** [comment]
The linked document is complete for now. We can update as we go if we deem it insufficient.
