### ISSUE TITLE
Make Cognito redirect URLs configurable in browser application

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#502]
### Overview
Update references to the redirect URLs for Cognito in the React application

### Action Items
* Establish a configuration convention for the React application, e.g. use a json or xml config format, env file
* Create the configuration for the redirect URI for HUU tenant in AWS Cognito
* Reference the configured value in all statements requiring the redirect URL

### Resources/Instructions
The redirect URL tells Cognito where to send a user after authentication. The HomeUniteUs client application is deployed in a variety of environments, e.g. `dev-ec2`, `test-ec2`, `prod-ec2`, `host-local`, `docker-local`.  Each of these may have different URLs where the client app is hosted, which the app will need to specify in requests to Cognito for signin/signup functionality to work

**Comment by sanya301** [comment]
@tylerthome has this actually been completed? I see it in the Done section but issue is not closed
