### ISSUE TITLE
Section 2 : Coordinator : View and Take action on Applications

### ISSUE THREAD

**Issue by rpradheap** [hackforla/HomeUniteUs#517]
###  The Problem

Coordinators should be able to view and take appropriate action on all applications submitted by Guest and host 

1. Application that are submitted 
2. Applications that are approved/ Declined 
3. Applications that are ready to be matched
4. Applications that are matched
5. Applications that have contract in place

#### User Story:

As a Coordinator,I should be able to view and take action on all applications so I can make sure that I take actions on applications in a timely manner

###  High Level Approach

Coordinator is able to view application on any stage and take action on add notes as required 

###  Considerations

 Coordinators will be using desktop or tablet--> use responsive design

###  Acceptance criteria
Success is if Coordinator can successfully 

1. Click the application from the dashboard page - sub pages to view it
2. Take action on application  such as approved, declined or ask for more info
3. Add comments if applicable on the decision or info 
4. After taking action - the appropriate status of application gets reflected 

### Key Features

Take Action Button: Coordinator clicks this and the application gets assigned to the co-ordinator and the co-ordinator is able to take action such as approved, declined on the application.

###  Design
https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?node-id=2353%3A17352&t=ZM7AykeF7WVNoXkD-0

- [ ] Review Existing Design 
- [ ] Update Design as Needed
- [ ] Designs are edited and ready for engineering. Link to the Figma: (share Figma link here when ready)

 
### Limitations

None

#### Team Reviews:

- [x] Product - Raji
- [ ] Design - Help Needed
- [ ] Engineering - Help Needed

**Comment by jasika-ai** [comment]
As a coordinator, I want to have access to a list of checklist items against each application to ensure smooth tracking of the application.

Acceptance criteria 

- The coordinator can view a dedicated checklist section within the application's dashboard for each application.
- The coordinator can mark checklist items as complete or incomplete. A visual indicator, such as a checkmark, indicates the completion status of each checklist item.
- If a checklist item is marked as incomplete, the coordinator can add comments or notes for his reference.

**Comment by sanya301** [comment]
Let's re-review this next time, please use #500 as example

**Comment by sanya301** [comment]
Use "Profile review page" for the sub page after clicking on intake profile

**Comment by sanya301** [comment]
@rpradheap this seems to be for the same functionality as https://github.com/hackforla/HomeUniteUs/issues/635, can you close one and use just one

**Comment by sanya301** [comment]
We also need a text box while taking action to record any notes

**Comment by rpradheap** [comment]
This has been added to issue:https://github.com/hackforla/HomeUniteUs/issues/635. So closing this one.
