### ISSUE TITLE
API: Remove dependency on swagger-cli bundle

### ISSUE THREAD

**Issue by paulespinosa** [hackforla/HomeUniteUs#539]
### Overview
The API currently needs to bundle the OpenAPI specification YAML files located in the API source code under `openapi_server/openapi` into a single file using the `swagger-cli bundle` tool because the `connexion` framework does not support the specifications spread across files. This issue is to remove this requirement so that the OpenAPI specification files in `openapi_server/openapi` can be used directly by the API code.

### Action Items
Research getting `connexion` to use the `openapi_server/openapi` spec files. Take a look at the comment on the connexion issue [Breaking up large swagger.yaml files
](https://github.com/spec-first/connexion/issues/254#issuecomment-1203427194) for ideas.

### Resources/Instructions
https://github.com/spec-first/connexion/issues/254 - a connexion issue about this problem
https://python-jsonschema.readthedocs.io/en/stable/referencing/ - the underlying library that parses the specs
https://referencing.readthedocs.io/en/stable/ - a referencing library used by jsonschema might have the ability to piece together separate files

**Comment by erikguntner** [comment]
Looks like [prance](https://github.com/RonnyPfannschmidt/prance) could potentially be what we are looking for.
https://github.com/spec-first/connexion/issues/254#issuecomment-497194240

**Comment by paulespinosa** [comment]
> Looks like [prance](https://github.com/RonnyPfannschmidt/prance) could potentially be what we are looking for. [spec-first/connexion#254 (comment)](https://github.com/spec-first/connexion/issues/254#issuecomment-497194240)

This looks very promising.

**Comment by erikguntner** [comment]
Looks like this is fixed in Connexion 3, which is currently in Alpha.

https://github.com/spec-first/connexion/pull/1648

**Comment by erikguntner** [comment]
It worked! I'll try to open a PR tonight. I just need to replace where _spec was being referenced and replace it.

**Comment by paulespinosa** [comment]
> Looks like this is fixed in Connexion 3, which is currently in Alpha.
> 
> [spec-first/connexion#1648](https://github.com/spec-first/connexion/pull/1648)

It's good to see they are addressing this. Too bad it's still in Alpha at the moment, but can be something to look forward to.
