### ISSUE TITLE
Resend confirmation email

### ISSUE THREAD

**Issue by erikguntner** [hackforla/HomeUniteUs#542]
### Overview
Users need a way to request resending the confirmation email after signing up.

### Action Items
Create an endpoint that takes the user's email as a parameter and resends the confirmation email.

### Resources/Instructions
Boto3 docs for resending confirmation code:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp/client/resend_confirmation_code.html

Link to the Figma frame:
https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?type=design&node-id=6764-95252&mode=design&t=qXPmdmA4atJvkami-4

**Comment by lola3736** [comment]
@paulespinosa please review complexity and point label for accuracy, make any necessary changes if needed.
