### ISSUE TITLE
Goals: August 2023

### ISSUE THREAD

**Issue by brycelednar** [hackforla/HomeUniteUs#545]
# Goals: August 2023

By 8/31/23: 

Designs for:
- [x] Global Navigation Bar - mobile #552 
- [ ] Host Dashboard #508 
- [ ] Coordinator Dashboard #501 
- [ ] Guest Application #533 
- [ ] Host Application #509 

Eng:
- [ ] Automated deployment for infrastructure

**Comment by brycelednar** [comment]
**8 29 23 Team Meeting Notes**

Host Dashboard 
- Check with design

Coordinator Dashboard 
- Waiting on design, designs to review for next week
- Raji - working on search and filter

Guest Application 
- Design in process
- Sanya working through the open question on e signatures

Host Application 
- Upcoming, will follow Guest Application

Eng:

Automated deployment for infrastructure
- Git workflow to build site and deploy to EC2 (replaces manual deploy process) done
- AWS networking infra automation; more research needed and details on timing and deadline for the deployment
- REST API auth - research in progress. Goal (in progress) working toward end of next month for a PR.

**Comment by sanya301** [comment]
@brycelednar since we moved leftover goals to the September issue, can we close this one?

**Comment by brycelednar** [comment]
Covered in September goals
