### ISSUE TITLE
Research Possibilities of Decoupling OpenAPI and SwaggerUI from API/Flask app

### ISSUE THREAD

**Issue by ju1es** [hackforla/HomeUniteUs#553]
### Overview
The purpose of this issue is to find any alternatives for integrating OpenAPI and SwaggerUI in a way that makes testing, documentation, and maintenance easier. 

### Action Items
- [ ] Outline current state of how OpenAPI and SwaggerUI are implemented in our API.
- [ ] Research (if any) options for decoupling OpenAPI and SwaggerUI from Flask app.
- [ ] List pros and cons of options.

### Resources/Instructions
[benefits of openapi discussion](https://news.ycombinator.com/item?id=36144674)
[openapi docs](https://flask-rest-api.readthedocs.io/en/stable/openapi.html)
[swaggerui docs](https://flask-restplus.readthedocs.io/en/0.4.2/swaggerui.html)

**Comment by Joshua-Douglas** [comment]
I put together a research plan and demo project to explore the essential features needed by a tool like `connexion`. See the [PP](https://github.com/Joshua-Douglas/PythonRestAPIExamples/blob/main/OpenAPI_API_Tools.md) for full detail.

I discussed this PP with the team today during the weekly meeting, and we agreed that there does not seem to be a compelling reason to replace `connexion` at this time. 

There were a few members missing from the meeting, so I'll revisit the topic at next week's meeting. If anyone identifies additional issues with `connexion`, these will be explored before closing this issue.

**Comment by Joshua-Douglas** [comment]
We discussed the linked project plan with the team over the last two weeks, and we've decided to continue using OpenAPI & connexion.
