### ISSUE TITLE
Introduce API Endpoint Authentication

### ISSUE THREAD

**Issue by Joshua-Douglas** [hackforla/HomeUniteUs#577]
### Overview
Introduce secure API endpoint authentication, so that only registered users can access our API. The selected authentication approach should be compatible with our current use of AWS Cognito, and should be integrated with the frontend app.

### Action Items
- [ ] Research the available API authentication methods. Choose the approach that works best for our application and create a high-level for the required API changes
- [ ] Review design and chosen authentication method with team, to solicit feedback before beginning implementation
- [ ] Update our OpenAPI specification to reflect the required authentication method. Note that some endpoints, such as SignUp, will not be authenticated
- [ ] Use connexion's authentication system to enforce the authentication methods documented in the OpenAPI specification
- [ ] Design a system for managing developer and test credentials. We will likely need to either bypass authentication during development/testing, or provide a secure mechanism for easily requesting and storing developer credentials
- [ ] Update the backend and frontend test cases to utilize the test credential system
- [ ] Update the frontend app to integrate with the new authentication system. We will need to ensure that the client HTTP requests have the required authentication headers. This can be made easy using cookies or sessions.

### Resources/Instructions
* [AWS Cognito Documentation](https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/Welcome.html)
* [Flask Security and Authentication](https://flask.palletsprojects.com/en/2.0.x/security/)
* [Connexion Authentication](https://connexion.readthedocs.io/en/latest/security.html)
* [Flask-login](https://flask-login.readthedocs.io/en/latest/)

**Comment by Joshua-Douglas** [comment]
To ensure that the frontend app signin workflow continues to work I plan on introducing a suite of end-to-end integration tests that verify that our authentication works before and after these changes. 

I began writing the test cases, but those test cases discovered a bug in the `session` and `refresh` endpoints that needs to be addressed before the test cases can pass. 

This bug was documented in #633. My plan is to keep this issue in the ice box until #633 is completed, since:
1) this suite of test cases will be very valuable for this issue
2) I plan to make some useful refactors to the session and refresh endpoints in #633 that will make closing this issue easier

**Comment by agosmou** [comment]
@Joshua-Douglas 
[Connexion 3.0 was released](https://connexion.readthedocs.io/en/3.0.2/security.html) - might be good to keep in mind if any of your implementation has the possibility to be depracated sooner with 2.0

**Comment by Joshua-Douglas** [comment]
Closed by #641. We can now easily test authenticated endpoints, and there is a clear separation between test users and real users. Endpoints that require authentication are protected by AWS Cognito. Now that we have a suite of test cases against the auth system, we are free to refactor our auth logic as needed in the future, and we should be able to avoid regressions.
