### ISSUE TITLE
Introduce tools to simply use of Marshmallow

### ISSUE THREAD

**Issue by Joshua-Douglas** [hackforla/HomeUniteUs#578]
### Overview
We will introduce the use of the marshmallow library in PR [575](https://github.com/hackforla/HomeUniteUs/pull/575). Marshmallow allows us to easily define database model schema, which allow us to easily serialize database tables as Json. Within this PR the schema are defined manually, but the [marshmallow-sqlalchemy](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/index.html) extension library has a `SQLAlchemyAutoSchema` class that can automatically generate schema using sqlalchemy metadata. 

### Action Items
- [ ] Explore using the `marshmallow-sqlalchemy` extension within our API, to determine if it simplifies schema definitions enough to justify using. 
- [ ] The `marshmallow-sqlalchemy` extension also works well with the `flask-marshmallow` extension. What does this extension do, and is this worth adding
- [ ] If the extensions are worth using, then restructure the connexion app configuration to ensure the extensions are properly initialized. These extensions both require some initialization
- [ ] Determine if it is possible to use these extensions to create sqlalchemy objects using json that has been validated by `connexion`. We can currently serialize table objects into json, but we cannot deserialize json into table objects. The ability to do this quickly will help us handle larger json bodies, such as forms

### Resources/Instructions
* Besides the libraries linked above, here is a RealPython demo repository that shows how to use these extensions: https://github.com/realpython/materials/tree/master/flask-connexion-rest-part-3

**Comment by stevbark** [comment]
Created pull for autoSchema. https://github.com/hackforla/HomeUniteUs/pull/648. currently all tests pass and opening all endpoints works correctly though I did not see any endpoint that directly interacted with these changes yet.

pull request: https://github.com/hackforla/HomeUniteUs/pull/648
