### ISSUE TITLE
API: Update connexion to 2.14.2, indirectly update Flask to 2.3.x series

### ISSUE THREAD

**Issue by paulespinosa** [hackforla/HomeUniteUs#580]
### Overview
Update `connexion` to 2.14.2 and `Flask` to the 2.3.x series. Also, allow their transitive dependencies to be updated.

### Action Items

- [x] Review the change logs of [`connexion`](https://github.com/spec-first/connexion/releases) and [`Flask`](https://flask.palletsprojects.com/en/2.3.x/changes/)
- [x] Note the deprecations that happen when updating `Flask` from the **2.2.x** series to the **2.3.x** series
- [x] Update the API to address the deprecations and other necessary changes needed to be made to the API
- [x] Update connexion to 2.14.2. Doing this will indirectly update Flask to a version in the 2.3.x series. Allow for their transitive dependencies to be updated.
- [x] Test the API/Run the API

### Resources/Instructions
`connexion` release notes: https://github.com/spec-first/connexion/releases
`Flask` release notes: https://flask.palletsprojects.com/en/2.3.x/changes/

**Comment by Joshua-Douglas** [comment]
Hey @johnwroge,

I think this would be a great first issue to work on! You'll need to build the backend and run the backend test cases to complete this issue. The [main README](https://github.com/hackforla/HomeUniteUs/blob/main/README.md) has docker build instructions, and the [api README](https://github.com/hackforla/HomeUniteUs/blob/main/api/README.md) has local build instructions. Building locally will be easier, but I think the README is less detailed. 

If you run into build error feel free to ping me or the dev slack channel. If you do find that the README is out of date, please update it as well!

**Comment by johnwroge** [comment]
Hi Joshua! 

Thank you so much for the assignment and for the additional information! I looked over the ReadMe for the API directory and it's very well written. If I run into any issues with building and testing the api I will make a note and reach out. Paul sent over the .env file for to connect so I should be good to start this task today.
