### ISSUE TITLE
API: Migrate SQLAlchemy 1.4.x to 2.0.x

### ISSUE THREAD

**Issue by paulespinosa** [hackforla/HomeUniteUs#581]
### Overview
SQLAlchemy is part of the data persistence layer of the API. The API is currently using a version from the 1.4.x series. Migrate the SQLAlchemy from 1.4.x to 2.0.x.

### Action Items

- [ ] Review the [SQLAlchemy 1.4 to 2.0 migration guide](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html) 
- [ ] Migrate the API code to use SQLAlchemy 2.0
- [ ] Help merge existing API PRs with new changes

### Resources/Instructions
Use the migration guide to help perform the migration: https://docs.sqlalchemy.org/en/20/changelog/migration_20.html

**Comment by shawnkoong** [comment]
The main change for our codebase with SQLAlchemy 2.0 is with the ORM queries. With 1.x, you can use `session.query` to query the database. With 2.0, the former is replaced with `session.execute` in most cases. For simpler queries such as `session.query(entity).get(PK)` or others that query a single row with PK can be translated simply to `session.get(entity, PK)`.

Examples of translating from 1.x style to 2.0 style can be found [here](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-orm-usage).
