### ISSUE TITLE
Make API base URL configurable in browser application

### ISSUE THREAD

**Issue by paulespinosa** [hackforla/HomeUniteUs#584]
### Overview

Currently, the base URL for the API is hardcoded to `http://localhost:4040/api` in the front-end application. However, the API's URL should be configurable.

Update to add context https://github.com/hackforla/HomeUniteUs/issues/584#issuecomment-1707579200 (thanks @Joshua-Douglas):

> This issue was necessary to properly use our build-deploy-ec2.yml and build-dev-workflow.yaml workflows. If the application is deployed with the hard coded URL then some features of the deployed app, such as sign in & sign up, will not work.

### Action Items

- [x] Update the API's base URL in `api.ts` to be obtained by an environment variable (e.g. from a `.env` file). The variable can be written as `import.meta.env.VITE_HUU_API_BASE_URL`.
- [x] Add an entry to `vite-en.d.ts` with `readonly VITE_HUU_API_BASE_URL: string;`.
- [x] Add `VITE_HUU_API_BASE_URL=http://localhost:4040/api` to `.env.example`.
- [x] Add `VITE_HUU_API_BASE_URL` as a GitHub environment variable (Tyler or Erik) 

### Resources/Instructions

[Vite environment variables for production](https://vitejs.dev/guide/env-and-mode.html#production-replacement)

Related #502

**Comment by Joshua-Douglas** [comment]
For additional context, this issue was necessary to properly use our `build-deploy-ec2.yml` and `build-dev-workflow.yaml` workflows. If the application is deployed with the hard coded URL then some features of the deployed app, such as sign in & sign up, will not work.

**Comment by lola3736** [comment]
@paulespinosa please review the complexity label for accuracy, change accordingly if required.
