### ISSUE TITLE
Assist with migrating deployment to Terraform

### ISSUE THREAD

**Issue by nyarly** [hackforla/HomeUniteUs#585]
### Overview

Hello there!

The Ops team is changing the way we deploy applications in Incubator, and we need the help of someone on this project to accomplish that. Thanks in advance!

There was a `project.hcl` file created and edited by a member of this project at one point - they'll need to be the one to participate.

### Action Items

There's an epic issue that describes the overall process: hackforla/incubator#20 

Please follow the guide there to effect the Terraform migration of this project's deployment!

### Resources/Instructions
The Issue above has all the details you should need. We're using it as a central clearinghouse, so we'll updating it with any new information or clarifications so that we can help everybody. 

Please reach out to @nyarly (@Judson on slack) or @JasonEb (same handle) with any questions.

**Comment by paulespinosa** [comment]
@tylerthome do you have the `project.hcl` file?

**Comment by paulespinosa** [comment]
Hey @nyarly, @tylerthome is searching for the `project.hcl`. We've been using a separate (outside of incubator) EC2 instance for testing, and it is likely that we'll start building the incubator from scratch if we can't locate the file.

**Comment by madcharlie02** [comment]
@paulespinosa Bonnie and I have access to project.hcl files -  maybe we can help you? Which ones do you need?

**Comment by paulespinosa** [comment]
@madcharlie02 The one that's referenced at https://github.com/hackforla/incubator/blob/bda977e67e562189397bcfdde1bec65d4813ba11/incubator/projects-prod/home-unite-us-api/terragrunt.hcl#L9.

Since Home Unite Us hasn't been using the incubator, we can build a new terraform incubator from the ground up.

**Comment by ExperimentsInHonesty** [comment]
@paulespinosa Sounds good.  We did look through 1password for the hcl files, but there weren't any for Home Unite Us

It would be good to get a written update of your progress.

Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by paulespinosa** [comment]
@tylerthome has created a new issue in HUU repo to track creation of a new terraform configuration for the incubator at #627

**Comment by paulespinosa** [comment]
@bonniewolfe I'll close this issue since it focuses on migrating whereas we have begun working on a new terraform configuration from scratch.

**Comment by lola3736** [comment]
@paulespinosa please review the complexity and points label assigned for accuracy, change accordingly if needed.
