### ISSUE TITLE
Section 2 | Guest Profile Submission

### ISSUE THREAD

**Issue by sanya301** [hackforla/HomeUniteUs#589]
### The Problem:
Currently, Guests have no means to fill out a profile to provide information about themselves that they would want to share with hosts.

### User Story:
As a Guest, I should be able to fill out a profile that the host will get to see.

### High-Level Approach:
Guest profile page with a place to fill out information guests can share with hosts. The page should also contain options like edit and save.

#### Considerations

- In the future, the plan is for the guest onboarding experience for multiple organizations (SPY and beyond), where different organizations might want to modify the profile needed for Guests.
- Anticipate that users will be using desktop, tablet, mobile devices --> use responsive design

### Goals & Success
Success is if a guest can successfully complete their Profile, as well as edit and submit it.

### Metrics
- Number of profiles completed vs the number of profiles started.
- Average time taken to complete each profile

### Key Features:

- Open paragraph for profile with question from [Guest profile text Link - see page 10](https://drive.google.com/file/d/0B3o4rAE_DB1IdUZiSHpDZ1NpOHpQWndCdGFnUWdBNHA3b0Zj/view?usp=sharing&resourcekey=0-pwCyBvvVPCownU3MjGEZcQ)
- Save button to save the profile and exit
- Autosave feature (nice to have, quick feedback from eng is that this should be possible, would need to identify events that trigger autosave eg changing a radio button selection)
- Ability to see the same saved profile after logging in if the user clicked save application button before exiting
- Ability to edit the profile multiple times before completing it.
- Ability to see a final overall preview before submitting the profile.
- Button to submit the final profile.
- Ability to edit the profile if requested by the coordinator.

### Acceptance Criteria:

- Guest Profile should unlock once Guest Application form has been submitted
- A guest should be able to edit the profile until it is submitted.
- Guest should see an error if they attempt to save a Profile that is empty
- Guest should be able to fill the Profile in multiple sessions by saving the Profile using a save button on the page (The save button will add all the filled questions into the database for this particular guest) 
- Guest should be able to see a preview of the profile before the final submission.
- Guest should be able to see pre-filled text for any sections that were saved at any point. If a guest is logged in and has exited before submitting the Profile, they should be able to continue the Profile from the dashboard page under the profile section.
- Guest should be able to submit the Profile which will lock the Profile and send it for review to the coordinator.
- Guest should not be able to start the matching process until the Guest Profile is completed and accepted
- Once the guest has submitted the Profile, they should see the Profile status as  pending review on the dashboard page.
- If a coordinator finds any issues with the Profile:
     - The guest should see a Edit requested status on the application tab of the dashboard and would receive an email/call from the coordinator on what needs to be edited
     - Profile should be unlocked for the Guest to edit it
     - Guest should be able to resubmit the Profile for review
- Guest should see completed status on the Profile once it has been approved by the co-ordinator, and be able to click into their profile at any point from the dashboard Profile section, or via navigation for the user profile
- Once guest application and profile has been approved, the matching section should unlock

### Future Consideration:

- Ability to add photos pending discussion with SPY and other host home programs

### Guest profile physical form:
[Guest profile text Link - see page 10](https://drive.google.com/file/d/0B3o4rAE_DB1IdUZiSHpDZ1NpOHpQWndCdGFnUWdBNHA3b0Zj/view?usp=sharing&resourcekey=0-pwCyBvvVPCownU3MjGEZcQ)

### Design

- [ ] Review existing designs on Figma
- [ ] Edit existing designs as needed
- [ ] Designs are edited and ready for engineering. Link to the Figma: (share Figma link here when ready)

### Engineering
- [ ] #636

### Team Reviews:

- [ ] Product - Sanya
- [ ] Design -
- [ ] Engineering -

### Open Questions:

- Customer open question: should paragraph answers have a minimum character count?

**Comment by sanya301** [comment]
Guest profile review page (what will be visible to the host) will be a separate user story

**Comment by sanya301** [comment]
This was merged with Guest Intake Profile (formerly known as application form) https://github.com/hackforla/HomeUniteUs/issues/533 
Closing this story

**Comment by jasika-ai** [comment]
Need to open this ticket again because the current design does not include 'upload picture' feature. Found notes in Figma that state **"Thanks for your interest SPY’s Host Home program. The sign up wizard will ask you to confirm details from your Host Home application, as well as upload a picture to introduce you."**
[https://www.figma.com/design/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?node-id=4926-114416&t=09j4rvggKxMvk0Y3-0](legacy design)

**Comment by jasika-ai** [comment]
Closing this issue as there is a new flow that captures the functionality.
