### ISSUE TITLE
Pre-login and post-login split header

### ISSUE THREAD

**Issue by JpadillaCoding** [hackforla/HomeUniteUs#590]
### Overview
Remove authentication from the header on pre-login pages. This includes clean-up of any code related to authentication on avatars, conditional renderings, etc.

### Action Items
- [x] Make a separate header renders for pre-login users
- [x] Remove code related to authorized users
- [x] Remove the MUI dropdown menu since the logo is the dropdown menu with #574 
- [x] Test split headers for functionality 

### Resources/Instructions
[Figma designs](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?type=design&node-id=370-0&mode=design&t=MPvLZ2cZZcEuSk96-0)

**Comment by Joshua-Douglas** [comment]
Hey @JpadillaCoding,

Last week you mentioned that you wanted to work this issue. Sounds like @erikguntner and @mira-kine might be able to provide the best support if you need some guidance. I'm also glad to help - but am still coming up to speed on TypeScript myself.

**Comment by JpadillaCoding** [comment]
@Joshua-Douglas Thanks! I will get started on it once #573 goes through since it has the new authenticated header on that branch.

**Comment by erikguntner** [comment]
@JpadillaCoding I merged #573. You should be good to go

**Comment by JpadillaCoding** [comment]
Notes: 
- Can use the ``useAuth`` hook for verifying if a user is logged in. This can be found in ``src > app > hooks > useAuth.ts``

**Comment by JpadillaCoding** [comment]
@erikguntner Can you help me to understand the function of the onClick prop in ``AuthenticatedHeader.tsx``? 
I am making a conditional to render the unauthenticated header vs the authenticated header. I am coming to an issue of not knowing what to pass to make the component functional.

**Comment by erikguntner** [comment]
>  Can you help me to understand the function of the onClick prop in AuthenticatedHeader.tsx

The onClick prop is a handler that gets passed to the mobile hamburger menu button to control a drawer. You can see how it is used in `DashboardLayout.tsx`. I can see how this could be confusing though. My thought process was to leave some flexibility in what that button controls.

Where are you writing the conditional? I was thinking we could use the unauthenticated header in a container to wrap the unauthenticated routes and then a different container with the authenticated header that wraps authenticated routes. So for this issue, it would just be removing the elements related to an authenticated user in the header which wraps the unauthenticated routes.

Something like this: 
```
// uses unauthenticated header
<AppContainer>
   // unauthenticated routes
</Appcontainer>

// authenticated header 
<GuestDashboard>
  // Routes for an authenticated guest
</GuestDashboard>

// authenticated header 
<HostDashboard>
  // Routes for an authenticated host
</HostDashboard>

// authenticated header 
<CoordinatorDashboard>
  // Routes for an authenticated coordinator
</CoordinatorDashboard>
```

And then in the future only render the authenticated routes when a user is logged in, and when we have RBAC, only render the routes related to the user type.

**Comment by JpadillaCoding** [comment]
> Where are you writing the conditional?

@erikguntner My approach was to modify the ``Header.tsx`` component into an unauthorized header. Then modify ``AppLayout.tsx`` to render between the authenticated and unauthenticated component depending on if a user is logged in. 

Regarding the approach to the headers- 
In this case of wrapping the header depending on the route, I would remove the ``Header`` component from ``AppLayout.tsx`` and work on wrapping the routes in its corresponding header- authorized or unauthorized. Also, Since we're wrapping the routes then the hamburger toggle needs to be passed through props. Am I understanding this correctly?

**Comment by erikguntner** [comment]
@JpadillaCoding  `AppLayout.tsx` already wraps all the unauthenticated routes, so if you make the modifications to `Header.tsx` you should be good to go. No need to remove `Header.tsx` from the layout component. Then there are just 3 protected routes that are still wrapped by `AppLayout.tsx`: `/coordinator`, `/profile`, and `/host`. You can remove `/profile` since that isn't needed anymore. Then we just need to do what we did for the guest dashboard for the host and coordinator routes. 

> Also, Since we're wrapping the routes then the hamburger toggle needs to be passed through props. Am I understanding this correctly?

I passed the prop more so we wouldn't have to include the drawer within the component in case other layouts called for different drawers or functionality.

**Comment by JpadillaCoding** [comment]
@erikguntner Ahh okay I understand now. Thanks!

**Comment by erikguntner** [comment]
@JpadillaCoding No problem! Let me know if anything else comes up.

**Comment by JpadillaCoding** [comment]
@erikguntner Do you happen to know why the ``CoordinatorDashboard`` component is used for two different routes on ``main.tsx``? 
It is used as ``/coord`` and ``/coordinator``. If it is redundant then I can delete on this issue.

**Comment by erikguntner** [comment]
@JpadillaCoding good catch. You can get rid off `/coord`.

**Comment by JpadillaCoding** [comment]
@erikguntner Since I am working on the headers, would it be appropriate to change the logo to adhere to these designs? They are using different sizes based on the device. Currently, we just have one logo for all devices. https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?type=design&node-id=2353-17350&mode=design&t=9A0Uivte341DNel6-0

**Comment by erikguntner** [comment]
@JpadillaCoding If not mistaken, those are older designs and it was decided that the logos were all too big. So we're sticking with the smaller one used now.
