### ISSUE TITLE
Host vs Coordinator Selection Page UI

### ISSUE THREAD

**Issue by mira-kine** [hackforla/HomeUniteUs#594]
### Overview
Currently, the page where a user chooses host vs coordinator before signing up is not mobile responsive. This issue is to fix the responsivity of the icons as well as fix the icons to match the updated design.

### Action Items

- Change icons to current updated design
- Fix responsivity of mobile view

**Comment by sanya301** [comment]
@tylerthome @erikguntner  do you know if this is still a bug?
