### ISSUE TITLE
Unifying Sign In and Sign Up Password Validation Schemes

### ISSUE THREAD

**Issue by mira-kine** [hackforla/HomeUniteUs#595]
### Overview
Currently Sign In and Sign Up have different special character validation schemes, preventing password unification. 

### Action Items
- unify the Sign In and Sign Up password validation scheme for special characters - currently the Sign In password scheme does not take special characters like `*` and `;`

**Comment by sanya301** [comment]
@mira-kine @erikguntner this had a missing feature label, I added it to tech debt, lmk if that's accurate
