### ISSUE TITLE
Provision operations infrastructure on AWS

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#62]
### Overview
Create an EC2 instance with Ubuntu server and install NGINX, Python, Flask, Gunicorn and MongoDB

### Action Items
- [x] Create EC2 instance with Ubintu
- [x] Install nginx, Python 3, pip and gunicorn
- [x] Install Python packages Flask and pymongo
- [x] Configure nginx to proxy requests to gunicorn
- [x] Coordinate configurations between webpack and Flask instance so that builds are automatically available to service

**Comment by c-fuchs** [comment]
Project is currently on Digital Ocean, will be redeployed on AWS pending further discussion regarding architecture. Ops call will discuss on 4/29 call

**Comment by tylerthome** [comment]
Closing as duplicate of issue #206

**Comment by lola3736** [comment]
@tylerthome please review points and complexity label for accuracy.
