### ISSUE TITLE
BL LOR

### ISSUE THREAD

**Issue by randelbrot** [hackforla/HomeUniteUs#624]
### Overview
Working session for LOR

### Action Items
* Context on request
* Review [LOR template inputs](https://docs.google.com/document/d/1q9CmTR0Z_zhifTUK8GbSp5jD2A_eFlDzH9FP_HvoukI/edit#heading=h.ezgfyvdpmpn9)
* Working session
* Discuss any next steps

**Comment by lola3736** [comment]
@bonniewolfe please review labels and confirm.
