### ISSUE TITLE
Dockerize application

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#63]
### Overview
Create a Dockerfile for the Host Home web application environment

### Action Items
- [x] Develop Dockerfile to mirror current EC2 deployment
- [x] Write a script `dockerize.sh` to build the Docker image from the Host Home source repository
- [x] Integration test resulting Docker image to ensure correctness

### Resources/Instructions
Reference issue #62 for more information on environment setup

**Comment by tylerthome** [comment]
As of PR #102 this issue is resolved. Note that shell scripts added to `scripts` directory are named differently than specified by this ticket, as it was determined that a more granular set of procedures was better suited to fit the requirement

**Comment by lola3736** [comment]
@tylerthome please review points and complexity for accuracy.
