### ISSUE TITLE
Section 2 - Coordinator- Clone Application/Reopen Application of Guest

### ISSUE THREAD

**Issue by rpradheap** [hackforla/HomeUniteUs#634]
### The Problem

In case more info is required to process the application, Coordinators should be able to create a new prefilled application that Guest or host can provide more info and submit the application again.

####  User Story:

As a coordinator, 
I should be able to request more information so that the Guest or Host can resubmit the application.

### High Level Approach

1. Coordinator Changes the status of application to More info needed. This will automatically create a new prefilled application of the Guest or Host. In the backend the Status will be Application Denied- More info needed.
2. Status of new application: Application more info needed
3. In the guest/ Host Dashboard please replace the existing application with the duplicate application as coordinator will most probably say that the application has been reopened and to add more info in field x,y and z to get it approved.

###  Considerations

Coordinators will be using desktop or tablet--> use responsive design

###  Acceptance criteria
Success is if Coordinator can successfully select the application status as Application Denied: more info needed
Guest or host is able to see the new prefilled application on their dashboard page and continue the application.

###  Key Features
None

###  Design
https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?node-id=2353%3A17352&t=ZM7AykeF7WVNoXkD-0

 Review Existing Design
 
- [ ] Updating Design as Needed
- [ ]  Designs are edited and ready for engineering. Link to the Figma: (share Figma link here when ready)
- [ ] Limitations

Coordinator may not be able to see applications that are yet to be submitted by Guest/Host

#### Team Reviews:

- [ ]  Product - Raji
- [ ]  Design - Help Needed
- [ ]  Engineering - Help Needed

**Comment by sanya301** [comment]
> as coordinator will most probably say that the application has been reopened and to add more info in field x,y and z to get it approved.

Can we rephrase this, it is confusing? One suggestion:

Guest/host dashboard should just say more info needed with edit application. The action that the coordinator will take will be to email or call the guest/host and explain the fields that need to be edited and resubmitted for review.

**Comment by sanya301** [comment]
>  Application Denied: more info needed
Can we distinguish between backend status and UI component. I think for UI we can just say more info needed

**Comment by sanya301** [comment]
Guest/host will no longer be signing the application so can we remove that as well

**Comment by rpradheap** [comment]
closing this issue. Please refer to this issue for the details - https://github.com/hackforla/HomeUniteUs/issues/635
