### ISSUE TITLE
Create Python helper tools for interacting with mongodb

### ISSUE THREAD

**Issue by KarlenS** [hackforla/HomeUniteUs#64]
### Overview
Add mongodb interaction Python helper functions.

### Action Items
Functions (basically CRUD) to add:
- Add hosts/guests/matchResults
- Fetch hosts/guests/matchReslts
- Update hosts'/guests' info/matchResults
- Remove hosts/guests/matchResults

### Resources/Instructions
Quick first pass Python functions to abstract out mongodb operations.

**Comment by salice** [comment]
Debugged the basic CRUD Flask routes, working on integrating Karlen's Mongo utility functions with the Flask routes
