### ISSUE TITLE
Section 2: Coordinator - Link to view Guest/Host Intake Profile

### ISSUE THREAD

**Issue by rpradheap** [hackforla/HomeUniteUs#656]
### The Problem
Currently, Coordinator do not have a digital way to manage applications (approve, deny, ask for changes) and everything has to be done in an ad hoc way.

#### User Story:
As a coordinator, I should be able to view  the application submitted by Guest/Host so I can take action(approve, deny, ask for more info) on the  application

### High Level Approach
- For Host applications - The dashboard will have an entry in the coordinator dashboard only when the Host submitted the application and the Host profile should be viewable on clicking the applicant's name.
- For Guest applications- Coordinator Dashboard should have the link to profile disabled until the Guest submits the application. The entry will be there before submitting on the dashboard to track the invitation sent to the guest.

### Considerations
Coordinators will be using desktop or tablet--> use responsive design

### Goals and Success
Success if coordinator can successfully view the link and are able to see the Intake profile of Guest and Host

### Metrics

None

### Key Features

- Link to Guest/host profile View Intake Profile on coordinator dashboard 
- On clicking the Link In take Profile - a separate window opens with the Intake Profile submitted by Guest/Host

### Acceptance Criteria
Success is if Coordinator can successfully view the guest/host Intake profile once the guest/host submits the application

### Known Limitations
Coordinator may not be able to see the profile that are yet to be submitted by Guest/Host

### Design

https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?node-id=2353%3A17352&t=ZM7AykeF7WVNoXkD-0

- [ ] Review existing designs on Figma
- [ ]  Edit existing designs as needed
- [ ]  Designs are edited and ready for engineering. Link to the Figma: (share Figma link here when ready)
- [ ] Limitations

#### Team Reviews:

- [ ] Product - Raji
- [ ]  Design - Help Needed
- [ ]  Engineering - Help Needed

**Comment by sanya301** [comment]
Please rename applications to intake profile everywhere @rpradheap

**Comment by sanya301** [comment]
- "Currently, Coordinator do not have the ability to View Guest and Host Intake Profile digitally." In the problem description though, there is no concept of an intake profile in the current coordinator world, so here actually we might want to say application to refer to the physical form they currently fill out
- I would add that there is no digital way to manage applications (approve, deny, ask for changes) and everything has to be done in an ad hoc way

**Comment by rpradheap** [comment]
added to issue #635
