### ISSUE TITLE
Add Search Filter for Coordinator Dashboard

### ISSUE THREAD

**Issue by mira-kine** [hackforla/HomeUniteUs#678]
### Overview
We need to add a search filter pop up to the coordinator dashboard so that the user can easily filter through the data for specific criteria.

### Action Items
- [ ] Add drop down UI for search filtering
- [ ] Add checkboxes with correct criteria
- [ ] Add optional search box in each of the drop down menus

The UI is according to this final design (*updated for June 2024):

<img width="446" alt="Screenshot 2024-06-09 at 5 54 46 PM" src="https://github.com/hackforla/HomeUniteUs/assets/90009901/cff2ed80-41bf-4f5f-96ad-6a14e75d38ae">

**Comment by erikguntner** [comment]
Design updates for this are coming:
https://www.figma.com/design/BNWqZk8SHKbtN1nw8BB7VM/HUU-Everything-Figma-Nov-2022?node-id=13092-6269&t=dSoPtekz7UCswguX-4

**Comment by lasryariel** [comment]
The search functionality that exists in https://dev.homeunite.us/coordinator is sufficient to move forward. Closing this issue.

![image](https://github.com/user-attachments/assets/45a13e5f-7be5-4d1b-a180-9a3afea18a5b)

![image](https://github.com/user-attachments/assets/5e9f9b23-a6ff-4bfe-871f-170b62859930)
