### ISSUE TITLE
Migrate HomeUniteUs to Incubator AWS account

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#686]
### Overview
Work with the HackForLA Ops team to integrate HomeUniteUs infrastructure terraforms and connect to shared environment from project GitHub Actions

### Action Items
- [ ] Ensure IaC deployment pipeline in incubator repository
- [ ] Complete HUU Terraform definitions
- [ ] Create/update actions and patterns/conventions for automated deployments
- [ ] Document processes and train a backup

### Resources/Instructions
* https://github.com/hackforla/incubator
* https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
* https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_oidc.html#idp_oidc_Create_GitHub

**Comment by tylerthome** [comment]
Opened related PR in separate repo related to this effort: https://github.com/hackforla/devops-security/pull/25

**Comment by sanya301** [comment]
@tylerthome any updates here
