### ISSUE TITLE
Link accounts and stop Google account creation from the sign in page

### ISSUE THREAD

**Issue by erikguntner** [hackforla/HomeUniteUs#703]
### Overview
Currently, users who sign in using a Google account that isn't associated with an existing account creates a user that has no role.
We can account for this in two ways: 

1. Linking accounts in the case the user wants to attach a Google account to their current email and password account.
2. If the user has not been saved in our database, meaning they haven't gone through the sign up process, we delete the created AWS user and throw an error.

### Action Items
- [x] Create a pre-sign-up lambda function to link AWS user accounts
- [ ] In the sign in endpoint, check if a user exists in our db, if not, delete the AWS user and throw error.

**Comment by sanya301** [comment]
Can you post update here?
