### ISSUE TITLE
Prep project boards for Migration

### ISSUE THREAD

**Issue by lasryariel** [hackforla/HomeUniteUs#705]
### Overview
We need to prepare the Project Boards for the forced migration that GitHub is doing in August, so that it is already working well for the team by then.

#### All cards on the main project board are backed up and moved to appropriate places
- [x]  copy this template to a comment below
   ````
   ### Text from project board card
   ```
   [INSERT MARKDOWN HERE]
   ```
   - [ ] Determine where this item goes on the wiki (page and section)
   - [ ] copy item to wiki
   - [ ] hide this comment when completed.
   ````
- [x] copy markdown from a card in the "Start Here" column of the Project Board into your new comment where it says `[INSERT MARKDOWN HERE]
- [x] delete card from project board. - Ariel Archived rather than deleting (5/31)

#### All issues are on the project board
- [x] check to see if all issues are on the project board (resource 1.02) - completed by Ariel 5/31
- [x] if not, add them to the board, and put them in the correct columns - completed by Ariel 5/31

#### Copy all content off persona board
- [x] Copy each card info into spreadsheet (resource 1.04) completed by Ariel 5/31
- [x] Close [Personas and User Stories Project](https://github.com/hackforla/HomeUniteUs/projects/6) - Ariel added this task and completed it (5/31), not sure if that is what Bonnie wanted but I don't see why we wouldn't.
- [ ] Categorize (can be done later)

### Resources/Instructions
- 1.01 main Project board: https://github.com/hackforla/HomeUniteUs/projects/3
- 1.02 [issues not on the project board](https://github.com/hackforla/HomeUniteUs/issues?q=is%3Aopen+is%3Aissue+-project%3Ahackforla%2Fhomeuniteus%2F3+)
- 1.03 [Persona project board](https://github.com/hackforla/HomeUniteUs/projects/6)
- 1.04 [Persona board transfer spreadsheet](https://docs.google.com/spreadsheets/d/1wJg1u7pBLRaiuebMPzkg-juLu3RRspEegRYlkE3LBx8/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card
```
#Weekly Tasks:
[All Team Meeting Agenda](https://github.com/hackforla/HomeUniteUs/issues/691)
[PM Meeting Agenda](https://github.com/hackforla/HomeUniteUs/issues/692)
[PM/Org Meeting Agenda](https://github.com/hackforla/HomeUniteUs/issues/364)
[Board Check](https://github.com/hackforla/HomeUniteUs/issues/354)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by lasryariel** [comment]
### Text from project board card
```
### Meeting Times And Links

#### General Team Meeting:
Every Tuesday at 6:30PM Pacific

#### PM Team Meeting:
Every Thursday at 7:00 PM Pacific

#### Design Team Meeting:
Every Tuesday 7PM Pacific
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by lasryariel** [comment]
### Text from project board card
```
#### Internal Links
- [Wiki](https://github.com/hackforla/HomeUniteUs/wiki)
- [Google drive](https://drive.google.com/drive/u/0/folders/1ahxiD9rIsBtx0yAPlPcPaGw8zGrfHHm9)
- [Roster](https://docs.google.com/spreadsheets/d/1Qp0iLv5Bvafip9y8gu9AUy2d5800916ybJ4_YElmyYM/edit#gid=1806338047)
- [Product Requirements Doc](https://docs.google.com/document/d/1sU7F-86Cywzaj4hBEx2Li76axOMaeqk4MIABXojmGF8/edit)

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by lasryariel** [comment]
### Text from project board card
```
#### Current Links to site
- [Development Site](https://dev.homeunite.us) - where we accept prs
- [Test Site](https://test.homeunite.us) where we push prs to for stakeholder acceptance
- [Production Site](https://homeunite.us) live site

- original spy demo (frozen) -> Please bring this back
- [Temporary login](https://homeuniteus.lacommunity.site/) 
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by lasryariel** [comment]
### Text from project board card
```
#### Design Links
[Miro](https://miro.com/app/board/o9J_lSssM10=/)
[Zeroheight](https://huu.zeroheight.com/styleguides)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by lasryariel** [comment]
### Text from project board card
```
### Stakeholder communication

#### WIP Stakeholder Communication for Pilot Kickoff
- [Pilot presentation](https://docs.google.com/presentation/d/1KTRPdK6jeSXTmmwxDOYGUNtzzNCFIGv-wAbv-pI77VY/edit#slide=id.ge14719f4d4_0_711)
- [PSY specific meeting](https://docs.google.com/presentation/d/1RPobOs-5yJ3_Ug3kTOSCoHXMBQdEKiF44sJgQnh3gfI/edit#slide=id.p)
- [Shareable Stakeholder Presentation](https://docs.google.com/presentation/d/1OgdJREqlUzFhpKRIBqRSihuA_WEaNay_lsTuD7IPA9g/edit#slide=id.gb7f12d851c_0_5)

#### Docs from Stakeholders 
- [Point Source Youth host home handbook](https://drive.google.com/file/d/1kxs7y-mjOZxdMw-Brf_MU3cUuffHD0q3/view?usp=sharing)
- [SPY Host Home application documents](https://drive.google.com/drive/u/0/folders/1PZzzGa8yEPn-wNEibCSDQkP3KikMs73e)

#### Stakeholder presentations
- [Spy Presentation 1.29](https://docs.google.com/presentation/d/1j-ZOqLaP72S3632LNC-931XkvD4nNLwA/edit#slide=id.p5)

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by lasryariel** [comment]
### Text from project board card
```
#### Figma Links

[Home Unite Us Team account](https://www.figma.com/files/team/1038532702107525096/Home-Unite-Us-Team?fuid=874021811757242268)

- [Current HomeUniteUs everything board](https://www.figma.com/file/BNWqZk8SHKbtN1nw8BB7VM/Current-HUU-Everything-Figma?node-id=0%3A1)

- [Calendaring HomeUniteUs](https://www.figma.com/file/FrIY32ZqKGJxl3VQNoGgPg/Calendaring-Home-Unite-Us?node-id=22%3A2)

- [Historical HUU board](https://www.figma.com/file/BJL6ZHfjrxVhU8jvD9gB3P/HomeUniteUs-Everything-Figma)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by lasryariel** [comment]
### Text from project board card
```
#### Interfaces
- Coordinator Interface
- Guest Interface
- Host Interface

#### Major Features
- [Coordinator Dashboard](https://github.com/hackforla/HomeUniteUs/projects/3?card_filter_query=label%3A%22p-feature%3A+dashboard+coordinator%22)
- Guest & Host Applications (Forms)
- IDM (Identity Management)(User Accounts)
-- Host Self-Registration
-- Guest Invitation
-- Coordinator account creation
-- Account Permissions
- Calendaring
- Guest/Host Matching System
- Messaging
- Files/Documents
-- Contract Submission (Special File Type)

#### User Flows
-  [Master Flow Diagram](https://www.figma.com/file/txIjeqdoE0G6YpEotDMLJe/HUU---Major-Flows?node-id=0%3A1)

#### [Requirements Lists](https://github.com/hackforla/HomeUniteUs/projects/3?card_filter_query=label%3Arequirements)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by lasryariel** [comment]
### Text from project board card
```
Coordinator Dashboard: Master https://github.com/hackforla/HomeUniteUs/projects/3#card-66265691
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by lasryariel** [comment]
I completed all the prep tasks. Remaining work is to go through all the comments and add them to the Wiki

**Comment by lasryariel** [comment]
This card also needs to be added elsewhere, I think the Wiki is probably appropriate too:

<details><summary>Text for recruitment process</summary>
<p>

<img src="https://user-images.githubusercontent.com/26660349/114799694-38cb3a80-9d66-11eb-8b08-78bdc1b653b3.png" />

**Project Name**: Home Unite Us 

**About the Project**: Help connect homeless youth with open rooms.

**Volunteer Opportunity**: Home Unite Us 
is looking for a UI Designer to contribute to our UI/UX Team. We are pushing towards our next milestone of completing a functional prototype. Role will execute designs in Figma based on established design system and product requirements.

[Project Overview On Github](https://github.com/hackforla/HomeUniteUs/blob/main/README.md)

Duration: Open Ended (3-6 hrs / week)
Team Meetings: 6:30 - 7PM Pacific Tuesdays
Design Team Meetings: 7 - 8PM Pacific Tuesdays

Who to communicate your interest to:
Slack Channel: [#home-unite-us](https://hackforla.slack.com/archives/CRWUG7X0C)
Contact Regan


</p>
</details>

**Comment by sanya301** [comment]
@lasryariel can we close this issue?

**Comment by lasryariel** [comment]
> @lasryariel can we close this issue?

@sanya301 I will now. I just added everything to the Wiki.
