### ISSUE TITLE
HUU: Open Role for: Product Manager

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/HomeUniteUs#725]
<img src="https://user-images.githubusercontent.com/26660349/114799694-38cb3a80-9d66-11eb-8b08-78bdc1b653b3.png" />

**Project Name**: Home Unite Us

**About the Project**: The Home Unite Us project is developing a workflow management tool for community non-profits to automate and scale their existing Host Home initiatives. Host Home programs are centered around housing 18-25 years old by matching a willing host with a guest or group of guests, providing a stable housing environment for youths who are experiencing homelessness and seeking stable housing.

**Volunteer Opportunity:** Looking for a PM to take over Coordinator persona stories as current PM will be leaving soon. Huge plus if you have enterprise experience

**Duration**: Ongoing

**Meeting Times**: 
- Product Owner meeting: Tues 6pm PST
- Team meetings: Tues 6:30pm PST
- PM meetings: Thurs 7pm PST

**Who to communicate your interest to**
- Slack channel link: [#home-unite-us-pm](https://app.slack.com/client/T04502KQX/C03QPG1B1K2)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/home-unite-us)

**Comment by lasryariel** [comment]
This was an old posting that got migrated to new system but is not needed.
