### ISSUE TITLE
HUU: Open Role for: UI/UX Researcher

### ISSUE THREAD

**Issue by lasryariel** [hackforla/HomeUniteUs#735]
<img src="https://user-images.githubusercontent.com/26660349/114799694-38cb3a80-9d66-11eb-8b08-78bdc1b653b3.png" />

**Project Name**: Home Unite Us

**Name of Role**: UI/UX Researcher

**Volunteer Opportunity**: We are looking for UI/UX Researcher to join our current team to help us finish creating our MVP!

**Duration**: On-going

**Meeting Times**: 
- Team meetings: Tuesdays 6:30pm PST
- Design meetings: Ad hoc as needed

**Who to communicate your interest to**
- Slack channel link: [home-unite-us-design](https://hackforla.slack.com/archives/C013XHCE99Q)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/home-unite-us)

**Comment by lola3736** [comment]
Recruited and onboarding candidates.
