### ISSUE TITLE
HUU: Open Role for: UI/UX Designers and Lead

### ISSUE THREAD

**Issue by lola3736** [hackforla/HomeUniteUs#738]
<img src="https://user-images.githubusercontent.com/26660349/114799694-38cb3a80-9d66-11eb-8b08-78bdc1b653b3.png" />

**Project Name**: Home Unite Us

**Name of Role**: UI/UX Design Lead

**Volunteer Opportunity**: Home Unite Us project, currently has needs for the following roles:
- A UI/UX Design Lead for the design team and collaborating with the Product and Engineering team. Huge plus if you have enterprise experience.
- 2 Design Product team members to collaborate with Product Manager and Engineering on finalizing automated workflow tool for MVP

**Duration**: On-going

**Meeting Times**: 
- Design meeting: Mon 7:00pm PST
- Team meetings: Tues 6:30pm PST

**Who to communicate your interest to**
- Slack channel link: [home-unite-us-design](https://hackforla.slack.com/archives/C013XHCE99Q)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/home-unite-us)
that helps with this issue provide the link(s) here. For example, a link to Figma, if applicable.

**Comment by duduyemi62** [comment]
Hi home unite us, I am interested in the UI/UX designer role

**Comment by kiyingi1** [comment]
hello @lola3736 , i wanna be getting started with anything available tomorrow. Please kindly reach out whenever you are available. Thank you

**Comment by lola3736** [comment]
Recruited and onboarded candidates.
