### ISSUE TITLE
Bug: API requirements.txt dependencies are wrong

### ISSUE THREAD

**Issue by paulespinosa** [hackforla/HomeUniteUs#746]
### Overview
Dependencies in `requirements.txt` and `requirements-dev.txt` were updated by `dependabot` causing version conflicts between `connexion` and `werkzeug`. 

API dependencies must be updated via `pyproject.toml` and using the tool `pip-compile` as described in `pyproject.toml`.

### Action Items
[X] Fix `pyproject.toml` because it contains a syntax error
[X] Run the `pip-compile` commands as documented in `pyproject.toml` to update the `requirements` files.

**Comment by lola3736** [comment]
@paulespinosa please add applicable features label, let me know if you have any questions.
