### ISSUE TITLE
Migrate Routes from Flask to Chalice

### ISSUE THREAD

**Issue by salice** [hackforla/HomeUniteUs#75]
### Overview
Take API routes from hosthome.py that are currently in Flask and turn them into Chalice routes. 

### Action Items
Install Chalice and set up aws credentials file with creds from Joel
Create app locally
### Resources/Instructions
Chalice Docs: https://chalice.readthedocs.io/en/latest/

**Comment by tylerthome** [comment]
Recommend closing this issue for now, pending discussion with development/management team about how tightly to couple (or not) our source code to AWS technology, then discuss the benefits

**Comment by ExperimentsInHonesty** [comment]
@tylerthome This sounds like a discussion to have at the Ops team.  Are you able to come next week (tuesdays at 8pm)?

**Comment by ExperimentsInHonesty** [comment]
We will not be pursuing this, since Sophia does not have time for the project
