### ISSUE TITLE
Failing weak password test on API

### ISSUE THREAD

**Issue by erikguntner** [hackforla/HomeUniteUs#759]
### Overview
We have a test that is failing on every PR.
<img width="992" alt="Screenshot 2024-08-21 at 6 38 12 PM" src="https://github.com/user-attachments/assets/57e83c30-ffbd-4690-ad20-a7a10258cccd">

### Action Items
[ ] Find out why test is failing and fix it

### Resources/Instructions
file path: `/api/tests/test_authentication.py`

**Comment by paulespinosa** [comment]
I see the problem is in the `admin_controller.remove_user` function.  The file might have had a bad merge at some point.
