### ISSUE TITLE
Create DyanmoDB Helper Functions

### ISSUE THREAD

**Issue by salice** [hackforla/HomeUniteUs#76]
### Overview
Create a class of helper functions to allow for the Chalice routes to access data from DyanmoDB

### Action Items
build out functions for CRUD operations to be used by Chalice routes

**Comment by tylerthome** [comment]
Related to issue #75 . Recommend closing until we determine the benefit of AWS lambda outweighs the tradeoff of tightly-coupling our codebase to Amazon-specific technologies
