### ISSUE TITLE
Create PM to Engineering Handoff Issue Template

### ISSUE THREAD

**Issue by lasryariel** [hackforla/HomeUniteUs#761]
### Overview
Using #745 as a reference, create a template for the PM team to use when a User Story is ready for engineering.

### Action Items
- [x] Create Template using #745
- [x] Create PR to pull to main repository #762
- [ ] Have admin approve PR

**Comment by lola3736** [comment]
@lasryariel is this issue still open? Lets discuss during team meeting on Thursday.
