### ISSUE TITLE
Initial Scaffold for FastAPI Implementation

### ISSUE THREAD

**Issue by lasryariel** [hackforla/HomeUniteUs#788]
- Parent Issue: #771

### Overview
This issue involves creating the foundational scaffold for our FastAPI implementation. The primary goal is to establish a starting point for the migration, focusing on user authentication (sign-in/sign-up) and ensuring early integration with the client interface. The new API should be testable from the client once the basic setup is complete.

### Action Items
- [x] Create a "trunk-type" branch named "fastapi-migration" branch in /api-v2 to manage the development of FastAPI migration.
- [x] Set up a new folder structure and add a basic scaffold for the FastAPI application.
- [x] Create updated [readme](https://github.com/hackforla/HomeUniteUs/tree/fastapi-migration/api-v2.)
- [x] Implement basic authentication endpoints:
    - [x] User Sign-In
    - [x] User Sign-Up
- [ ] Integrate the initial scaffold with the client to validate the API setup.
- [x] Review the scaffold and implementation progress with the team.

## Resources/Instructions
- **Poetry**: Use [Poetry](https://python-poetry.org/docs/) to manage dependencies for this FastAPI project.
- **FastAPI Docs**: [Official Documentation](https://fastapi.tiangolo.com/) for routing, dependency injection, and more.
- **Authentication**: Set up OAuth2 with JWT via [FastAPI Security](https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/).
- **Project Structure**: Organize your app using [Best Practices](https://fastapi.tiangolo.com/tutorial/bigger-applications/).
- **Testing**: Refer to [Testing FastAPI](https://fastapi.tiangolo.com/tutorial/testing/) for setting up automated tests.

**Comment by erikguntner** [comment]
Closed with #787

**Comment by lasryariel** [comment]
endpoints:

create session
get current user

Erik to open PR to connect frontend

move over remaining endpoints
invite guest endpoint
coordinator dashboard
Intake Profile

9 controllers
- [ ] admin_controller
- [ ] auth_controller
- [ ] cooridinator_controller
- [ ] forms_controller
- [ ] host_controller
- [ ] responses_controller
- [ ] security_controller
- [ ] service_provider_controller
- [ ] users_controller

might need to rearrange endpoints/controllers a bit
user endpoint moved into its own controller


Folder structuring
documentation
- diagram/descriptions
- important to document authentication process

**Comment by lasryariel** [comment]
Endpoints:

- [ ] /users/{userId}
- [ ] /serviceProviders
- [ ] /serviceProviders/{providerId}
- [ ] /host
- [ ] /auth/signup/host
- [ ] /auth/signup/coordinator
- [ ] /auth/signin
- [ ] /auth/resend_confirmation_code
- [ ] /auth/confirm
- [ ] /auth/signout
- [ ] /auth/session
- [ ] /auth/refresh
- [ ] /auth/forgot_password
- [ ] /auth/forgot_password/confirm
- [ ] /auth/user
- [ ] /auth/private
- [ ] /auth/google
- [ ] /auth/google/sign_up
- [ ] /auth/google/sign_in
- [ ] /auth/new_password
- [ ] /auth/invite
- [ ] /auth/confirmInvite
- [ ] /forms
- [ ] /forms/{form_id}
- [ ] /responses/{f

**Comment by lasryariel** [comment]
- Erik has auth related PR ready for review
- John working on invite guest end points
- Paul working on mock local dev environment

- Erik to review front end for cleanup (file moves, restructure, orphaned components, fastapi compatibility, documentation/best practices)
  - knowledge transfer before Erik starts job on 30th
