### ISSUE TITLE
Re-factor Frontend

### ISSUE THREAD

**Issue by timmalstead** [hackforla/HomeUniteUs#79]
### Overview
Refactor frontend in preparation for connection to a working backend

### Action Items
- [ ] contingent on backend working, remove hardcoded front end context data
- [ ] connect front end to back and ensure CRUD functions are working
- [ ] if necessary, refactor CRUD api functions to work with chosen database and server setup (i.e. flask/mongo, chalice/dynamo etc.)

**Comment by tylerthome** [comment]
Complete as of pull #109

**Comment by lola3736** [comment]
@tylerthome please review the complexity and points label for accuracy.
