### ISSUE TITLE
Create proposed FaaS architecture diagram

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#80]
### Overview
Create a diagram representing a proposed system architecture which uses AWS Lambda via Chalice as opposed to a traditional EC2 instance with Flask

### Instructions
 Using a diagramming tool, design a system architecture capable of supporting the necessary operation for the Host Home MVP

**Comment by tylerthome** [comment]
Related to issue #75 recommend closing until defined as a technical requirement, considering tradeoffs around vendor lock-in and potential upside

**Comment by lola3736** [comment]
@tylerthome please review points and complexity label for accuracy.
