### ISSUE TITLE
Introduce team to Eric at HS Lynk

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#95]
### Dependency
- When Slide Deck is finished - #317 

### Overview
Introduce team to Eric Jahn at HS Lynk to discuss if his platform would fit our needs.

### Action Items
Introduce Eric to Host Home team
Provide contacts for both back end leads and whole team email address

**Comment by c-fuchs** [comment]
Putting on hold pending Host Home team. We need to have a better-defined picture of how we want to interact with HS Lynk.

**Comment by tylerthome** [comment]
@ExperimentsInHonesty whether this issue is still important/urgent enough for a presence in our backlog merits a big picture discussion

**Comment by ExperimentsInHonesty** [comment]
@tylerthome @abbyhipp agreed.  Let's table this for discussion later.  We can put this into a tag for discussion around security.

**Comment by ExperimentsInHonesty** [comment]
We will be reaching out to Eric on pricing once we have slides to show him, so that he can give us details about pricing
